# Pydantic

## data classes

In [21]:
from dataclasses import dataclass

@dataclass
class Person():
    name:str
    age:int
    city:str

In Python, `dataclasses` (introduced in Python 3.7) are a way to simplify class creation when the class is mainly used to store data. A `dataclass` automatically generates special methods like `__init__`, `__repr__`, `__eq__`, and more, reducing boilerplate code.

---

### ✅ Use of `@dataclass`

The `@dataclass` decorator helps to:

* Auto-generate constructor `__init__()`
* Auto-generate string representation `__repr__()`
* Auto-generate comparison methods like `__eq__()`, `__lt__()`, etc.
* Support default values, type annotations, and immutability (`frozen=True`)
* Easily convert to and from dictionaries using `asdict()` and `astuple()`

---

### 🆚 Comparison: With and Without `@dataclass`

#### 🔴 Without `dataclass`

```python
class Person:
    def __init__(self, name: str, age: int):
        self.name = name
        self.age = age

    def __repr__(self):
        return f"Person(name={self.name}, age={self.age})"

    def __eq__(self, other):
        return self.name == other.name and self.age == other.age
```

You must manually write:

* `__init__` method
* `__repr__` for debugging
* `__eq__` to compare objects

---

#### ✅ With `dataclass`

```python
from dataclasses import dataclass

@dataclass
class Person:
    name: str
    age: int
```

You get all the above (`__init__`, `__repr__`, `__eq__`) **automatically**!

---

### ✅ Example: Using the `dataclass`

```python
from dataclasses import dataclass

@dataclass
class Product:
    id: int
    name: str
    price: float = 0.0  # default value

p1 = Product(1, "Laptop", 999.99)
p2 = Product(1, "Laptop", 999.99)

print(p1)           # Product(id=1, name='Laptop', price=999.99)
print(p1 == p2)     # True
```

---

### ✨ Bonus Features

* **Default values**:

  ```python
  @dataclass
  class User:
      name: str
      is_active: bool = True
  ```
* **Immutability**:

  ```python
  @dataclass(frozen=True)
  class ImmutablePoint:
      x: int
      y: int
  ```
* **Conversion**:

  ```python
  from dataclasses import asdict
  asdict(p1)  # {'id': 1, 'name': 'Laptop', 'price': 999.99}
  ```

---

### 🧠 Summary Table

| Feature           | Without `@dataclass` | With `@dataclass`  |
| ----------------- | -------------------- | ------------------ |
| Auto `__init__()` | ❌                    | ✅                  |
| Auto `__repr__()` | ❌                    | ✅                  |
| Auto `__eq__()`   | ❌                    | ✅                  |
| Less boilerplate  | ❌                    | ✅                  |
| Type safety       | Optional             | ✅ with annotations |
| Dict conversion   | Manual               | ✅ (`asdict()`)     |

---

Let me know if you want to compare `dataclass` with `NamedTuple`, `attrs`, or `pydantic` next.


In [22]:
person=Person(name="Krish",age=35,city="Bangalore")
print(person)

Person(name='Krish', age=35, city='Bangalore')


In [23]:
person=Person(name="Krish",age=35,city=35)
print(person)

Person(name='Krish', age=35, city=35)


Strict type checking was not performed by "dataclasses"

## Pydantic

In [24]:
from pydantic import BaseModel

In [25]:
class Person1(BaseModel):
    name:str
    age:int
    city:str

person=Person1(name="Krish",age=35,city="Bangalore")
print(person)

name='Krish' age=35 city='Bangalore'


In [26]:
# person1=Person1(name="Krish",age=35,city=35)
# print(person1)

---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[6], line 1
----> 1 person1=Person1(name="Krish",age=35,city=35)
      2 print(person1)

File c:\Users\saina\.conda\envs\agentic_2_base\Lib\site-packages\pydantic\main.py:253, in BaseModel.__init__(self, **data)
    251 # `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks
    252 __tracebackhide__ = True
--> 253 validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
    254 if self is not validated_self:
    255     warnings.warn(
    256         'A custom validator is returning a value other than `self`.\n'
    257         "Returning anything other than `self` from a top level model validator isn't supported when validating via `__init__`.\n"
    258         'See the `model_validator` docs (https://docs.pydantic.dev/latest/concepts/validators/#model-validators) for more details.',
    259         stacklevel=2,
    260     )

ValidationError: 1 validation error for Person1
city
  Input should be a valid string [type=string_type, input_value=35, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type

pydantic does strict type checking

In [27]:
person2=Person1(name="Krish",age=35,city="35")
print(person2)

name='Krish' age=35 city='35'


As "35" is string, Pydantic accepted 35 into city

## Model with Optional Fields

In [28]:
from typing import Optional
class Employee(BaseModel):
    id:int
    name:str
    department:str
    salary:Optional[float] = None #Optional with default value
    is_active:Optional[bool] = True #Optional with default value

In [29]:
emp1=Employee(id=1,name="John",department="CS")
print(emp1)

id=1 name='John' department='CS' salary=None is_active=True


Default values are taken in above instance

In [30]:
emp2=Employee(id=2,name="Krish",department="CS",salary="30000")
print(emp2)

id=2 name='Krish' department='CS' salary=30000.0 is_active=True


feasible type casting is able to done by pydantic

Definition:
- Optional[type]: Indicates the field can be None

- Default value (= None or = True): Makes the field optional

- Required fields must still be provided

- Pydantic validates types even for optional fields when values are provided

In [31]:
emp3=Employee(id=2,name="Krish",department="CS",salary="30000",is_active=1)
print(emp3)

id=2 name='Krish' department='CS' salary=30000.0 is_active=True


In [32]:
from typing import List

class Classroom(BaseModel):
    room_number:str
    students: List[str] #List of strings
    capacity:int

we can give data structures like list in data type of variables in pydantic

In [33]:
# Create a classroom
classroom = Classroom(
    room_number="A101",
    students=("Alice", "Bob", "Charlie"),
    capacity=30
)
print(classroom)

room_number='A101' students=['Alice', 'Bob', 'Charlie'] capacity=30


tuple converted to list by type casting.

In [34]:
list(("Alice", "Bob", "Charlie"))

['Alice', 'Bob', 'Charlie']

In [35]:
# # Create a classroom
# classroom1 = Classroom(
#     room_number="A101",
#     students=("Alice", 123, "Charlie"),
#     capacity=30
# )
# print(classroom1)

---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[14], line 2
      1 # Create a classroom
----> 2 classroom1 = Classroom(
      3     room_number="A101",
      4     students=("Alice", 123, "Charlie"),
      5     capacity=30
      6 )
      7 print(classroom1)

File c:\Users\saina\.conda\envs\agentic_2_base\Lib\site-packages\pydantic\main.py:253, in BaseModel.__init__(self, **data)
    251 # `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks
    252 __tracebackhide__ = True
--> 253 validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
    254 if self is not validated_self:
    255     warnings.warn(
    256         'A custom validator is returning a value other than `self`.\n'
    257         "Returning anything other than `self` from a top level model validator isn't supported when validating via `__init__`.\n"
    258         'See the `model_validator` docs (https://docs.pydantic.dev/latest/concepts/validators/#model-validators) for more details.',
    259         stacklevel=2,
    260     )

ValidationError: 1 validation error for Classroom
students.1
  Input should be a valid string [type=string_type, input_value=123, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type

list of strings only are accepted. So validation error

In [36]:
try:
    invalid_val=Classroom(room_number="A1",students=["Krish",123],capacity=30)

except Exception as e:
    print(e)

1 validation error for Classroom
students.1
  Input should be a valid string [type=string_type, input_value=123, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type


use try except block to print the concise error and does not stop the execution of notebook

In [37]:
from typing import List
from pydantic import BaseModel

class Classroom(BaseModel):
    room_number:str
    students: List[float] #List of floats
    capacity:int

In [38]:
class1 = Classroom(room_number="201",students = [1,2,3], capacity = 3)
print(class1)

room_number='201' students=[1.0, 2.0, 3.0] capacity=3


In [39]:
from typing import List
from pydantic import BaseModel

class Classroom(BaseModel):
    room_number:str
    students: List[str] #List of floats
    capacity:int

In [ ]:
# class1 = Classroom(room_number="201",students = [1,2,3], capacity = 3)
# print(class1)

ValidationError: 3 validation errors for Classroom
students.0
  Input should be a valid string [type=string_type, input_value=1, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
students.1
  Input should be a valid string [type=string_type, input_value=2, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
students.2
  Input should be a valid string [type=string_type, input_value=3, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type

---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[40], line 1
----> 1 class1 = Classroom(room_number="201",students = [1,2,3], capacity = 3)
      2 print(class1)

File c:\Users\saina\.conda\envs\agentic_2_base\Lib\site-packages\pydantic\main.py:253, in BaseModel.__init__(self, **data)
    251 # `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks
    252 __tracebackhide__ = True
--> 253 validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
    254 if self is not validated_self:
    255     warnings.warn(
    256         'A custom validator is returning a value other than `self`.\n'
    257         "Returning anything other than `self` from a top level model validator isn't supported when validating via `__init__`.\n"
    258         'See the `model_validator` docs (https://docs.pydantic.dev/latest/concepts/validators/#model-validators) for more details.',
    259         stacklevel=2,
    260     )

ValidationError: 3 validation errors for Classroom
students.0
  Input should be a valid string [type=string_type, input_value=1, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
students.1
  Input should be a valid string [type=string_type, input_value=2, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
students.2
  Input should be a valid string [type=string_type, input_value=3, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type

Great question!

You're getting a **validation error** because **Pydantic does not automatically cast `List[int]` to `List[str]`** — i.e., it won’t convert `[1, 2, 3]` into `["1", "2", "3"]` automatically for a field typed as `List[str]`.

---

### ⚠️ Here's the error you'll get:

```python
ValidationError: 1 validation error for Classroom
students -> 0
  str type expected (type=type_error.str)
```

This means:
Pydantic expected each item in `students` to be a **string**, but found an **integer** at index 0.

---

### ❓Why doesn't Pydantic cast `List[int]` → `List[str]`?

Because **element-wise coercion in collections is not automatic**.
This is to avoid silently introducing bugs — especially when the difference between types matters (e.g., `"10"` vs `10` in business logic).

---

### ✅ How to fix it

#### ✅ Option 1: Pass strings correctly

```python
class1 = Classroom(room_number="201", students=["1", "2", "3"], capacity=3)
```

#### ✅ Option 2: Use a custom validator if you still want automatic casting

```python
from pydantic import BaseModel, field_validator
from typing import List

class Classroom(BaseModel):
    room_number: str
    students: List[str]
    capacity: int

    @field_validator("students", mode="before")
    @classmethod
    def cast_all_to_str(cls, v):
        return [str(i) for i in v]

class1 = Classroom(room_number="201", students=[1, 2, 3], capacity=3)
print(class1)
```

---

### ✅ Output:

```python
room_number='201' students=['1', '2', '3'] capacity=3
```

---

### 🧠 Summary

| Behavior                       | Default in Pydantic |
| ------------------------------ | ------------------- |
| Cast `int` → `str`             | ✅ Yes               |
| Cast `List[int]` → `List[str]` | ❌ No                |

> You must handle element-wise coercion explicitly with a validator.

Let me know if you want reusable casting utilities for nested lists or dictionaries!


## Model with Nested Models

In [41]:
from pydantic import BaseModel

class Address(BaseModel):
    street:str
    city:str
    zip_code:str

class Customer(BaseModel):
    customer_id:int
    name:str
    address:Address  ## Nested Model

In [42]:
customer=Customer(customer_id=1,name="Krish",
                  address={"street":"Main street","city":"Boston","zip_code":"02108"})

print(customer)

customer_id=1 name='Krish' address=Address(street='Main street', city='Boston', zip_code='02108')


In [43]:
# customer=Customer(customer_id=1,name="Krish",
#                   address=["Main street","Boston","02108"])

# print(customer)

In nested model, dictionary should be used while instantiating.

In [44]:
# customer=Customer(customer_id=1,name="Krish",
#                   address={"street":"Main street","city":123,"zip_code":"02108"})

# print(customer)

---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[18], line 1
----> 1 customer=Customer(customer_id=1,name="Krish",
      2                   address={"street":"Main street","city":123,"zip_code":"02108"})
      4 print(customer)

File c:\Users\saina\.conda\envs\agentic_2_base\Lib\site-packages\pydantic\main.py:253, in BaseModel.__init__(self, **data)
    251 # `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks
    252 __tracebackhide__ = True
--> 253 validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
    254 if self is not validated_self:
    255     warnings.warn(
    256         'A custom validator is returning a value other than `self`.\n'
    257         "Returning anything other than `self` from a top level model validator isn't supported when validating via `__init__`.\n"
    258         'See the `model_validator` docs (https://docs.pydantic.dev/latest/concepts/validators/#model-validators) for more details.',
    259         stacklevel=2,
    260     )

ValidationError: 1 validation error for Customer
address.city
  Input should be a valid string [type=string_type, input_value=123, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type

## Pydantic Fields: Customization and Constraints


The Field function in Pydantic enhances model fields beyond basic type hints by allowing you to specify validation rules, default values, aliases, and more. Here's a comprehensive tutorial with examples.

In [45]:
from pydantic import BaseModel,Field

class Item(BaseModel):
    name:str=Field(min_length=2,max_length=50)
    price:float=Field(gt=0,le=10000)  ## greater than 0 and less than or equal to 1000
    quantity:int=Field(ge=0)

In [46]:
# item=Item(name="Book", price=100000,quantity=10)
# print(item)

---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[20], line 1
----> 1 item=Item(name="Book", price=100000,quantity=10)
      2 print(item)

File c:\Users\saina\.conda\envs\agentic_2_base\Lib\site-packages\pydantic\main.py:253, in BaseModel.__init__(self, **data)
    251 # `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks
    252 __tracebackhide__ = True
--> 253 validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
    254 if self is not validated_self:
    255     warnings.warn(
    256         'A custom validator is returning a value other than `self`.\n'
    257         "Returning anything other than `self` from a top level model validator isn't supported when validating via `__init__`.\n"
    258         'See the `model_validator` docs (https://docs.pydantic.dev/latest/concepts/validators/#model-validators) for more details.',
    259         stacklevel=2,
    260     )

ValidationError: 1 validation error for Item
price
  Input should be less than or equal to 10000 [type=less_than_equal, input_value=100000, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/less_than_equal

field is used for condition based input data validation

In [47]:
class User(BaseModel):
    username:str=Field(description="Unique username for the user")
    age:int=Field(default=18,description="User age default to 18 ")
    email:str= Field(default_factory=lambda: "user@example.com",description="Default email address")

In [48]:
# Examples
user1 = User(username="alice")
print(user1)

username='alice' age=18 email='user@example.com'


default factory is dynamic way of creating the default values, Can use datetime now in it.

To dynamically set the `email` field based on the `username` (like `alice@example.com`), you **cannot use `default_factory` alone**, because `default_factory` **doesn’t have access to other field values**.

Instead, use a **`@model_validator`** or `@root_validator` (for older Pydantic v1), which gives access to the entire model so you can compute one field based on another.

---

### ✅ Pydantic v2 Solution (Recommended)

```python
from pydantic import BaseModel, Field, model_validator

class User(BaseModel):
    username: str = Field(description="Unique username for the user")
    age: int = Field(default=18, description="User age defaults to 18")
    email: str = Field(default=None, description="Email will default to username@example.com")

    @model_validator(mode="after")
    def set_email_if_missing(self) -> 'User':
        if self.email is None:
            self.email = f"{self.username}@example.com"
        return self

# Example
user1 = User(username="alice")
print(user1)
```

---

### ✅ Output

```python
username='alice' age=18 email='alice@example.com'
```

---

### 🔎 How It Works

* `@model_validator(mode="after")`: This hook runs **after** all fields are parsed and validated.
* We check if `email` is missing (`None`), and if so, we compute it using `username`.

---

### ⚠️ Alternative (Pydantic v1)

If you're using Pydantic **v1**, use `@root_validator(pre=False)` instead:

```python
from pydantic import BaseModel, Field, root_validator

class User(BaseModel):
    username: str = Field(...)
    age: int = Field(default=18)
    email: str = None

    @root_validator
    def set_email(cls, values):
        if not values.get('email'):
            values['email'] = f"{values['username']}@example.com"
        return values
```

---

Let me know your Pydantic version if you’re unsure, and I’ll tailor the code to that.


## Schema from pydantic

In [49]:
User.model_json_schema()

{'properties': {'username': {'description': 'Unique username for the user',
   'title': 'Username',
   'type': 'string'},
  'age': {'default': 18,
   'description': 'User age default to 18 ',
   'title': 'Age',
   'type': 'integer'},
  'email': {'description': 'Default email address',
   'title': 'Email',
   'type': 'string'}},
 'required': ['username'],
 'title': 'User',
 'type': 'object'}

## What is Serialisation in pydantic

In **Pydantic**, **serialization** refers to **converting a Pydantic model (Python object) into a data format that can be easily stored or transferred**, such as **JSON, dictionaries, or strings**.

### ✅ In simpler terms:

**Serialization = Model → JSON or dict**

---

### 🔧 Common Use-Cases for Serialization:

* Sending data over an API (JSON format)
* Saving model data to a file or database
* Logging structured data

---

### 🧠 How it works in Pydantic:

Suppose you have a model:

```python
from pydantic import BaseModel

class User(BaseModel):
    id: int
    name: str
    email: str
```

#### ➤ `dict()` — serialize to Python dictionary:

```python
user = User(id=1, name="Alice", email="alice@example.com")
user_dict = user.dict()
print(user_dict)
```

Output:

```python
{'id': 1, 'name': 'Alice', 'email': 'alice@example.com'}
```

#### ➤ `json()` — serialize to JSON string:

```python
user_json = user.json()
print(user_json)
```

Output:

```json
{"id": 1, "name": "Alice", "email": "alice@example.com"}
```

---

### 🔄 Related Term: **Deserialization**

The reverse — converting from JSON or dict back to a Pydantic model:

```python
user_data = {'id': 1, 'name': 'Alice', 'email': 'alice@example.com'}
user = User(**user_data)
```

---

### 💡 Bonus: Custom Serialization

You can customize serialization using:

* `Config` class with `json_encoders`
* `model.dict(include=..., exclude=...)` to include/exclude fields
* Aliases and field customization with `Field(..., alias=...)`

---

Let me know if you'd like to see examples with nested models, custom field names, or datetime handling!


## Pydantic Crash course by CampusX
`https://github.com/campusx-official/pydantic-crash-course`

## Extra

class Item(BaseModel):
    id: str 
    email: str 


Is it possible to use id as a part in default factory of email? such that email default values is like id+"@gmail.com"

✅ **Yes, it’s possible** — but **not directly inside `Field(default_factory=...)`** because at the time `default_factory` runs, **other fields like `id` may not be initialized yet**.

However, Pydantic provides a clean way to do this using a **`model_post_init`** method in **Pydantic v2**, or a **`@root_validator`** in **Pydantic v1**.

---

### ✅ Pydantic v2: Use `model_post_init`

```python
from pydantic import BaseModel, Field
from uuid import uuid4

class Item(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid4()))
    email: str | None = None

    def model_post_init(self, __context):
        if self.email is None:
            self.email = f"{self.id}@gmail.com"
```

---

### ✅ Pydantic v1: Use `@root_validator`

```python
from pydantic import BaseModel, Field, root_validator
from uuid import uuid4

class Item(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid4()))
    email: str | None = None

    @root_validator(pre=False)
    def set_email(cls, values):
        if values.get('email') is None:
            values['email'] = f"{values['id']}@gmail.com"
        return values
```

---

### 🧪 Example usage:

```python
item = Item()
print(item.id)      # e.g., "8d3e8d72-1f75-43a4-9e1e-7b9e457dca8a"
print(item.email)   # e.g., "8d3e8d72-1f75-43a4-9e1e-7b9e457dca8a@gmail.com"
```

---

### 🧠 Why `Field(default_factory=...)` won't work here?

Because it doesn't **know about other fields** during execution — it just calls the function when no value is passed.

So for **dependent default values**, always use:

* `model_post_init` (Pydantic v2)
* `root_validator` (Pydantic v1)

---

Let me know your Pydantic version if you need a custom solution for your codebase!


## Difference between Field and field_validator

Great question! `Field` and `field_validator` in **Pydantic** serve **very different purposes**, though they both help you control and validate data.

---

### 🆚 `Field` vs `field_validator` — Core Differences

| Feature                       | `Field(...)`                                                                       | `@field_validator(...)`                                      |
| ----------------------------- | ---------------------------------------------------------------------------------- | ------------------------------------------------------------ |
| **Purpose**                   | Declare **defaults**, **metadata**, and **constraints**                            | Implement **custom logic** to validate or transform          |
| **Used for**                  | - Default values<br>- Descriptions<br>- Ranges (gt, lt)<br>- Aliases<br>- UI hints | - Conditional rules<br>- Data formatting<br>- Complex checks |
| **When it runs**              | During model schema parsing                                                        | During/after field value assignment (based on `mode`)        |
| **Declarative or imperative** | Declarative (like saying "must be > 0")                                            | Imperative (like writing Python logic)                       |
| **Return required?**          | ❌ No return value needed                                                           | ✅ Must return the (possibly modified) value or raise error   |

---

### 🔹 `Field(...)` – For Defaults, Constraints, and Metadata

```python
from pydantic import BaseModel, Field

class User(BaseModel):
    age: int = Field(..., gt=0, lt=100, description="Age must be between 1 and 99")
    name: str = Field(default="Anonymous", max_length=20)
```

✔️ It adds:

* Validation rules (e.g., `gt`, `lt`, `max_length`)
* Default values (`default`, `default_factory`)
* Schema metadata (`description`, `title`, `example`)

---

### 🔹 `@field_validator(...)` – For Custom Validation Logic

```python
from pydantic import BaseModel, Field, field_validator

class User(BaseModel):
    name: str
    email: str

    @field_validator('email')
    @classmethod
    def check_email(cls, v):
        if not v.endswith('@gmail.com'):
            raise ValueError("Email must be a gmail.com address")
        return v
```

✔️ It allows:

* Any Python logic
* Value transformation (like `.upper()`, formatting)
* Cross-field or deep validation (via `@model_validator` or `@root_validator`)

---

### 🧪 Example with Both

```python
from pydantic import BaseModel, Field, field_validator

class Product(BaseModel):
    name: str
    price: float = Field(gt=0, description="Price must be positive")

    @field_validator('name')
    @classmethod
    def strip_name(cls, value):
        return value.strip().title()
```

* `Field(gt=0)` ensures `price > 0`
* `@field_validator` formats `name` before storing

---

### ✅ Summary

| Aspect                                 | `Field`                         | `@field_validator` |
| -------------------------------------- | ------------------------------- | ------------------ |
| Controls defaults?                     | ✅ Yes                           | ❌ No               |
| Adds metadata for OpenAPI/docs?        | ✅ Yes                           | ❌ No               |
| Applies static validation constraints? | ✅ Yes (like `gt`, `max_length`) | ✅ If custom logic  |
| Good for dynamic validation?           | ❌                               | ✅ Yes              |
| Required to return value?              | ❌                               | ✅ Yes              |
| Runs on model creation?                | ✅                               | ✅                  |

---

Let me know if you want to explore how to **combine both** or use them in **Pydantic v2 with Annotated types**.


## Difference between field validator and model validator from pydantic? and any other validators present in it

Excellent question, Sainadh! Let’s break down the difference between **`field_validator`**, **`model_validator`**, and other available **validators in Pydantic v2**, along with when and why to use each.

---

### ✅ 1. `field_validator` – Validate or transform a **single field**

#### 🔹 Purpose:

Used to validate or transform the value of **one specific field** (before or after parsing).

#### 🔹 Syntax:

```python
@field_validator('field_name', mode='before' or 'after')
@classmethod
def validator_name(cls, value): ...
```

#### 🔹 When to use:

* Format or clean field values (`.strip()`, `.upper()`)
* Enforce field-specific rules (e.g., `email must end with @gmail.com`)
* Normalize types (e.g., convert strings to int)

#### 🔹 Example:

```python
from pydantic import BaseModel, field_validator

class User(BaseModel):
    name: str

    @field_validator('name')
    @classmethod
    def validate_name(cls, v):
        return v.title()
```

---

### ✅ 2. `model_validator` – Validate across **the entire model**

#### 🔹 Purpose:

Used to validate the model as a whole — **after all fields are parsed**, and useful when validation **depends on multiple fields**.

#### 🔹 Syntax:

```python
@model_validator(mode='before' or 'after')
@classmethod
def validate_model(cls, data): ...
```

#### 🔹 When to use:

* Validate relationships between fields (e.g., `start_date < end_date`)
* Conditionally require a field (`if x is True, y must be provided`)
* Post-process entire object

#### 🔹 Example:

```python
from pydantic import BaseModel, model_validator

class Booking(BaseModel):
    start: int
    end: int

    @model_validator(mode='after')
    @classmethod
    def check_duration(cls, model):
        if model.end <= model.start:
            raise ValueError('End must be after start')
        return model
```

---

### ✅ Other Validators in Pydantic v2

| Validator                            | Purpose                                                           |
| ------------------------------------ | ----------------------------------------------------------------- |
| `@field_validator`                   | Validate or transform **one field**                               |
| `@model_validator`                   | Validate the **entire model** (cross-field logic)                 |
| `@field_serializer`                  | Custom **serialization logic** for a field                        |
| `@model_serializer`                  | Custom **serialization** for the entire model                     |
| `@computed_field`                    | Define **derived read-only fields**                               |
| `@root_validator` (deprecated in v2) | Old way to validate models in v1 (replaced by `@model_validator`) |

---

### 🧠 Summary Table

| Feature                      | `field_validator`   | `model_validator`              |
| ---------------------------- | ------------------- | ------------------------------ |
| Validates one field?         | ✅ Yes               | ❌                              |
| Uses multiple fields?        | ❌                   | ✅ Yes                          |
| Transform values?            | ✅ Yes               | ✅ Yes                          |
| Before parsing?              | ✅ (`mode='before'`) | ✅ (`mode='before'`)            |
| After parsing?               | ✅ (`mode='after'`)  | ✅ (`mode='after'`)             |
| Replaces `@validator` in v1? | ✅ Yes               | ✅ (replaces `@root_validator`) |

---

### 🚨 Notes:

* Use `mode='before'` to validate **raw input** (before parsing/coercion).
* Use `mode='after'` to validate **parsed values** (after type enforcement).
* You must return the value (`field_validator`) or model (`model_validator`).

---

Let me know if you want:

* A cheatsheet of **all decorators in Pydantic v2**
* Examples of combining `Annotated` with `Field` and `field_validator`
* How these work with **FastAPI** or **custom error messages**


## What is computed field?

Great choice, Sainadh! In **Pydantic v2**, a `@computed_field` is used to **define a read-only, derived field** — one that **is not passed during model creation**, but is **computed from other fields**.

---

### 🔹 What is a `@computed_field`?

It’s like a **property** that gets **included in `.model_dump()` and `.json()`**, and can even show up in OpenAPI docs (if used with FastAPI).

---

### ✅ Use Case

* Calculate `full_name` from `first_name + last_name`
* Compute `total_price = quantity * unit_price`
* Convert `datetime` into a `formatted_str`

---

### ✅ Syntax

```python
from pydantic import BaseModel, computed_field

class Model(BaseModel):
    ...

    @computed_field
    @property
    def field_name(self) -> ReturnType:
        return ...
```

> You must annotate the return type. Otherwise, Pydantic will raise an error.

---

### 🧪 Example: Full Name from First & Last

```python
from pydantic import BaseModel, computed_field

class Person(BaseModel):
    first_name: str
    last_name: str

    @computed_field
    @property
    def full_name(self) -> str:
        return f"{self.first_name} {self.last_name}"
```

#### Usage:

```python
p = Person(first_name="Sainadh", last_name="Bahadursha")
print(p.full_name)  # Sainadh Bahadursha
print(p.model_dump())  # includes full_name!
```

---

### 🧪 Example: Total Cost

```python
class Item(BaseModel):
    name: str
    unit_price: float
    quantity: int

    @computed_field
    @property
    def total(self) -> float:
        return self.unit_price * self.quantity
```

---

### 🧠 Key Rules

| Rule                       | Explanation                            |
| -------------------------- | -------------------------------------- |
| Must return annotated type | Required: `-> str`, `-> float`, etc.   |
| Must be a `@property`      | It's always accessed like an attribute |
| Included in `model_dump()` | Even though it’s not part of input     |
| Read-only                  | Cannot be passed during model creation |

---

### ⚠️ Cannot assign it!

```python
p = Person(first_name="Sainadh", last_name="Bahadursha", full_name="Wrong")  # ❌ Error
```

It’s **computed only**, not assignable.

---

### ✅ Summary

| Feature                      | `@computed_field` |
| ---------------------------- | ----------------- |
| Read-only field?             | ✅ Yes             |
| Included in `.model_dump()`? | ✅ Yes             |
| Accept user input?           | ❌ No              |
| Used for?                    | Derived fields    |
| Pydantic v2 only?            | ✅ Yes (new in v2) |

---

Let me know if you want examples of `computed_field` used with `datetime`, nested models, or how to make it show in **FastAPI** Swagger docs!


In **Pydantic v2**, serialization is more customizable with two new features:

#### ✅ `@field_serializer`

Used to **customize how a single field** is serialized (i.e., converted to JSON or dict).

#### ✅ `@model_serializer`

Used to **customize how the entire model** is serialized.

These are useful when you want to:

* Format fields in a specific way for output
* Hide or transform data when exporting
* Implement custom JSON encodings

---

### 🔹 1. `@field_serializer` — Per Field Customization

#### 🧠 Purpose:

Customize how **a particular field** is serialized (e.g., hiding, masking, formatting dates, etc.)

#### ✅ Example: Masking an email field

```python
from pydantic import BaseModel, Field, field_serializer

class User(BaseModel):
    username: str
    email: str

    @field_serializer('email')
    def mask_email(self, email):
        user, domain = email.split('@')
        return f"{user[0]}***@{domain}"

u = User(username="alice", email="alice@example.com")
print(u.model_dump())   # {'username': 'alice', 'email': 'a***@example.com'}
```

---

### 🔹 2. `@model_serializer` — Full Model Customization

#### 🧠 Purpose:

Customize how the **entire model** is converted to a dictionary or JSON.

#### ✅ Example: Convert model to camelCase keys

```python
from pydantic import BaseModel, model_serializer

def to_camel(string: str) -> str:
    parts = string.split('_')
    return parts[0] + ''.join(word.capitalize() for word in parts[1:])

class Product(BaseModel):
    product_name: str
    in_stock: bool

    @model_serializer(mode='wrap')
    def camel_case_serializer(self, handler):
        data = handler(self)
        return {to_camel(k): v for k, v in data.items()}

p = Product(product_name="Phone", in_stock=True)
print(p.model_dump())  # {'productName': 'Phone', 'inStock': True}
```

---

#### 🔄 Comparison Table

| Feature       | `@field_serializer`             | `@model_serializer`                  |
| ------------- | ------------------------------- | ------------------------------------ |
| Scope         | Single field                    | Entire model                         |
| Use Case      | Formatting, masking, converting | Renaming keys, flattening, reshaping |
| Mode          | Default is `'plain'`            | `'plain'` or `'wrap'`                |
| Output Format | Controls just one field         | Controls the full dict/JSON          |

---

#### 🧪 Bonus: Combine Both

```python
class Employee(BaseModel):
    first_name: str
    last_name: str
    salary: float

    @field_serializer("salary")
    def mask_salary(self, value):
        return "Confidential"

    @model_serializer(mode="wrap")
    def serialize_full_name(self, handler):
        data = handler(self)
        data["full_name"] = f"{self.first_name} {self.last_name}"
        del data["first_name"]
        del data["last_name"]
        return data

e = Employee(first_name="John", last_name="Doe", salary=100000)
print(e.model_dump())
# {'salary': 'Confidential', 'full_name': 'John Doe'}
```

---

#### 🔚 Summary

| Decorator           | Purpose                                | Use When…                            |
| ------------------- | -------------------------------------- | ------------------------------------ |
| `@field_serializer` | You want to modify just **one field**  | e.g., mask email, format timestamp   |
| `@model_serializer` | You want to modify the **whole model** | e.g., rename keys, flatten structure |

---

Let me know if you want real-world use cases like hiding sensitive fields in API responses or converting nested models to flat ones.


# Lang Chain Expression Language

In [ ]:
from langchain_google_genai import GoogleGenerativeAIEmbeddings
embeddings = GoogleGenerativeAIEmbeddings(model = "models/embedding-001")
from langchain_google_genai import ChatGoogleGenerativeAI
llm = ChatGoogleGenerativeAI(model="gemini-2.0-flash")

In [ ]:
template= 'Hi! I am learning {skill}. Can you suggest me top 5 things to learn?\n'

In [ ]:
from langchain import PromptTemplate
prompt = PromptTemplate(template=template,input_variables=["skill"])
print(prompt)

input_variables=['skill'] input_types={} partial_variables={} template='Hi! I am learning {skill}. Can you suggest me top 5 things to learn?\n'


In [ ]:
from langchain import LLMChain
llm_chain = LLMChain(prompt=prompt,llm=llm)
print(llm_chain.run('Data Science'))

C:\Users\saina\AppData\Local\Temp\ipykernel_11400\2026417700.py:2: LangChainDeprecationWarning: The class `LLMChain` was deprecated in LangChain 0.1.17 and will be removed in 1.0. Use :meth:`~RunnableSequence, e.g., `prompt | llm`` instead.
  llm_chain = LLMChain(prompt=prompt,llm=llm)
C:\Users\saina\AppData\Local\Temp\ipykernel_11400\2026417700.py:3: LangChainDeprecationWarning: The method `Chain.run` was deprecated in langchain 0.1.0 and will be removed in 1.0. Use :meth:`~invoke` instead.
  print(llm_chain.run('Data Science'))


Okay, diving into Data Science is exciting! Here are my top 5 suggestions for things to learn, focusing on a balance of foundational knowledge and practical application, along with why each is important:

**1. Python (or R) Programming:**

*   **Why it's essential:** Python is the dominant language in data science due to its versatility, extensive libraries, and active community. R is another popular choice, particularly strong in statistical computing and visualization. You really only need to become deeply proficient in one to start.
*   **What to learn:**
    *   **Basic Syntax:** Variables, data types (integers, floats, strings, booleans), operators, control flow (if/else statements, loops).
    *   **Data Structures:** Lists, dictionaries, tuples, sets.
    *   **Functions:** Defining and calling functions, understanding scope.
    *   **Object-Oriented Programming (OOP):** Classes, objects, inheritance (especially helpful for larger projects).
    *   **Key Libraries (Python Focu

In [ ]:
print(llm_chain.run({'skill':'Data Science'}))

Okay, great! Data Science is a vast and exciting field. Here are my top 5 suggestions for things to learn as you're starting out, focusing on building a solid foundation:

1.  **Python Programming (with NumPy, Pandas, and Matplotlib/Seaborn):**

    *   **Why:** Python is the *lingua franca* of data science. It's used for everything from data manipulation and analysis to model building and deployment.  NumPy provides efficient numerical computation, Pandas is essential for data cleaning and manipulation, and Matplotlib/Seaborn are the go-to libraries for data visualization.
    *   **What to learn:**
        *   **Basic Python:** Variables, data types, control flow (if/else, loops), functions, object-oriented programming (classes and objects), file I/O.
        *   **NumPy:** Arrays, array operations (arithmetic, slicing, indexing, reshaping), linear algebra.
        *   **Pandas:** DataFrames, Series, data cleaning (handling missing values, duplicates), data manipulation (filtering, g

In [ ]:
chain = prompt | llm

In [ ]:
print(chain.invoke({'skill':'Big Data'}))

content="Okay, that's great!  Big Data is a fascinating and in-demand field.  Here are my top 5 things to learn, focusing on practical skills and understanding the ecosystem:\n\n1.  **Distributed Storage and Processing (Hadoop and/or Spark):**\n\n    *   **Why it's essential:** This is the foundation of big data.  You need to understand how to store and process massive datasets across a cluster of machines.\n    *   **What to learn:**\n        *   **Hadoop:**  HDFS (Hadoop Distributed File System) for storage, MapReduce for basic batch processing, and YARN for resource management.  While Spark is often preferred now, understanding Hadoop provides valuable context.\n        *   **Spark:**  Spark Core (for distributed computation), Spark SQL (for querying data), Spark Streaming (for real-time data processing), and possibly Spark MLlib (for machine learning).  Focus on the core concepts: RDDs (Resilient Distributed Datasets), DataFrames, and the execution model.\n        *   **Key Skills:

In [ ]:
from langchain_core.output_parsers import StrOutputParser

In [ ]:
parser = StrOutputParser()

In [ ]:
chain = prompt | llm | parser

In [ ]:
print(chain.invoke({'skill':'Machine Learning'}))

Okay, great! Machine Learning is a fascinating and rapidly evolving field. Here are my top 5 suggestions for things to learn as you're starting out, focusing on building a solid foundation:

1.  **Python Programming Fundamentals:**

    *   **Why:** Python is the dominant language in Machine Learning. You'll use it for data manipulation, model building, evaluation, and more.
    *   **Key Concepts:**
        *   **Data Types:** Integers, floats, strings, booleans.
        *   **Data Structures:** Lists, dictionaries, tuples, sets.  Understand when to use each.
        *   **Control Flow:** `if/else` statements, `for` and `while` loops.
        *   **Functions:** Defining and calling functions, parameters, return values.
        *   **Object-Oriented Programming (OOP) Basics:** Classes, objects, inheritance (a basic understanding is helpful, you don't need to be an expert).
        *   **File I/O:** Reading from and writing to files.
    *   **Libraries to Focus On:**
        *   **NumP

## Runnables

### Runnable Passthrough

In [ ]:
from langchain_core.runnables import RunnableParallel, RunnablePassthrough , RunnableLambda

In [ ]:
chain = RunnablePassthrough()

In [ ]:
chain.invoke('Hi this is sainadh')

'Hi this is sainadh'

In [ ]:
chain = RunnablePassthrough() | RunnablePassthrough() | RunnablePassthrough()

In [ ]:
chain.invoke('Hi this is sainadh')

'Hi this is sainadh'

### Runnable Lambda

In [ ]:
def string_upper(input):
  return input.upper()

In [ ]:
chain = RunnableLambda(string_upper)

In [ ]:
chain.invoke('Hi this is sainadh')

'HI THIS IS SAINADH'

In [ ]:
chain = RunnablePassthrough() | RunnableLambda(string_upper)

In [ ]:
chain.invoke('Hi this is Sainadh')

'HI THIS IS SAINADH'

In [ ]:
# string_upper.invoke('Hi this is sainadh')

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[34], line 1
----> 1 string_upper.invoke('Hi this is sainadh')

AttributeError: 'function' object has no attribute 'invoke'

### Runnable Parallel

In [ ]:
chain = RunnableParallel({'x':RunnablePassthrough(),'y':RunnablePassthrough()})

In [ ]:
chain.invoke("Hi this is Sainadh")

{'x': 'Hi this is Sainadh', 'y': 'Hi this is Sainadh'}

In [ ]:
chain.invoke({'First Name': 'Sainadh','Last Name': "Bahadursha"})

{'x': {'First Name': 'Sainadh', 'Last Name': 'Bahadursha'},
 'y': {'First Name': 'Sainadh', 'Last Name': 'Bahadursha'}}

In [ ]:
lambda x: x['Last Name']

<function __main__.<lambda>(x)>

In [ ]:
chain = RunnableParallel({'Name':RunnablePassthrough(),'Last Name':lambda x: x['Last Name']})

In [ ]:
chain.invoke({'First Name': 'Sainadh','Last Name': "Bahadursha"})

{'Name': {'First Name': 'Sainadh', 'Last Name': 'Bahadursha'},
 'Last Name': 'Bahadursha'}

In [ ]:
def fetch_email(input: dict):
    output = input.get('email','Not found')
    return output

In [ ]:
mydict={'First Name': 'Sainadh','Last Name': "Bahadursha"}

In [ ]:
mydict.get("email","Not found")

'Not found'

In [ ]:
chain = RunnableParallel({'email':RunnablePassthrough() | RunnableLambda(fetch_email),
                          'Last Name':lambda z: z['Last Name']})

In [ ]:
chain.invoke({'First Name': 'Sainadh','Last Name': "Bahadursha"})

{'email': 'Not found', 'Last Name': 'Bahadursha'}

In [ ]:
def extra_func(input):
    return 'Hello'

In [ ]:
chain = RunnableParallel({'x' : RunnablePassthrough()}).assign(extra=RunnableLambda(extra_func))

In [ ]:
chain.invoke('Sainadh')

{'x': 'Sainadh', 'extra': 'Hello'}

# Lang Chain Basics

## Loading the environment variables

In [101]:
import os
from dotenv import load_dotenv
load_dotenv()

True

In [51]:
os.getenv("LANGCHAIN_PROJECT")

'Agentic2.0'

In [102]:
os.environ["OPENAI_API_KEY"]=os.getenv("OPENAI_API_KEY")
os.environ["GROQ_API_KEY"]=os.getenv("GROQ_API_KEY")
os.environ["GOOGLE_API_KEY"]=os.getenv("GOOGLE_API_KEY")
os.environ["PINECONE_API_KEY"]=os.getenv("PINECONE_API_KEY")
## Langsmith Tracking And Tracing
os.environ["LANGCHAIN_API_KEY"]=os.getenv("LANGCHAIN_API_KEY")
os.environ["LANGCHAIN_PROJECT"]=os.getenv("LANGCHAIN_PROJECT")
os.environ["LANGCHAIN_TRACING_V2"]=os.getenv("LANGCHAIN_TRACING_V2")
os.environ["HF_TOKEN"]=os.getenv("HF_TOKEN")

## Langchain chatopenai

In [53]:
from langchain_openai import ChatOpenAI

llm=ChatOpenAI(model="o1-mini")
print(llm)

client=<openai.resources.chat.completions.completions.Completions object at 0x0000017548D97250> async_client=<openai.resources.chat.completions.completions.AsyncCompletions object at 0x0000017548E97E90> root_client=<openai.OpenAI object at 0x000001754618A350> root_async_client=<openai.AsyncOpenAI object at 0x00000175489CC950> model_name='o1-mini' temperature=1.0 model_kwargs={} openai_api_key=SecretStr('**********')


langchain chatopenai automatically extract openai_api_key from environment variables

In [54]:
result=llm.invoke("What is Agentic AI")
print(result)

content='**Agentic AI** refers to artificial intelligence systems designed to operate with a degree of autonomy, pursuing goals and making decisions independently to achieve specified objectives. The term "agentic" derives from "agent," emphasizing the AI\'s capacity to act on behalf of users or perform tasks without constant human oversight. Here\'s a comprehensive overview of what Agentic AI entails:\n\n### Key Characteristics\n\n1. **Autonomy**: Agentic AI systems can perform tasks and make decisions without continuous human intervention. They can adapt to changing environments and modify their actions based on real-time data.\n\n2. **Goal-Oriented Behavior**: These AI agents are designed with specific objectives in mind. They plan, execute, and adjust their strategies to accomplish predefined goals effectively.\n\n3. **Perception and Interaction**: Agentic AI can perceive its environment through sensors or data inputs and interact with it accordingly. This includes understanding co

In [55]:
print(result.content)

**Agentic AI** refers to artificial intelligence systems designed to operate with a degree of autonomy, pursuing goals and making decisions independently to achieve specified objectives. The term "agentic" derives from "agent," emphasizing the AI's capacity to act on behalf of users or perform tasks without constant human oversight. Here's a comprehensive overview of what Agentic AI entails:

### Key Characteristics

1. **Autonomy**: Agentic AI systems can perform tasks and make decisions without continuous human intervention. They can adapt to changing environments and modify their actions based on real-time data.

2. **Goal-Oriented Behavior**: These AI agents are designed with specific objectives in mind. They plan, execute, and adjust their strategies to accomplish predefined goals effectively.

3. **Perception and Interaction**: Agentic AI can perceive its environment through sensors or data inputs and interact with it accordingly. This includes understanding context, recognizing 

## Lang chain chat groq

In [56]:
from langchain_groq import ChatGroq
model=ChatGroq(model="qwen-qwq-32b")
model.invoke("Hi My name is Sainadh")

AIMessage(content='\n<think>\nOkay, the user introduced themselves as Sainadh. I should respond politely and maybe ask how I can assist them. Let me make sure to keep it friendly and open-ended. Maybe something like, "Hello Sainadh! How can I assist you today?" That should work. I don\'t need any special formatting here, just a simple greeting. Alright, send that.\n</think>\n\nHello Sainadh! How can I assist you today?', additional_kwargs={}, response_metadata={'token_usage': {'completion_tokens': 91, 'prompt_tokens': 17, 'total_tokens': 108, 'completion_time': 0.208324454, 'prompt_time': 0.003205764, 'queue_time': 0.392671625, 'total_time': 0.211530218}, 'model_name': 'qwen-qwq-32b', 'system_fingerprint': 'fp_18a313a21d', 'finish_reason': 'stop', 'logprobs': None}, id='run--42d1d496-5985-4dea-b4fd-5033b9bc7ae5-0', usage_metadata={'input_tokens': 17, 'output_tokens': 91, 'total_tokens': 108})

> qwen-qwq-32b

Here’s a detailed overview of **QwQ‑32B** — a powerful reasoning-oriented large language model:

---

### 🧠 What is QwQ‑32B?

* **Reasoning-specialized model**: Part of Alibaba Cloud's Qwen family, QwQ‑32B is specifically designed for deep analytical reasoning, surpassing general instruction-tuned models on complex, multi-step tasks ([medium.com][1]).
* **Size and architecture**:

  * \~32.5 B total parameters (\~31 B non-embedding)
  * 64 Transformer layers
  * 40 Q / 8 KV attention heads
  * Supports ultra-long context: up to 131,072 tokens ([huggingface.co][2]).

---

### ⚙️ Capabilities

* **Advanced reasoning**: Strong in math, coding, and challenging problem-solving—achieves top-tier results on benchmarks like AIME24, BFCL, LiveBench, competing closely with models up to 20× larger (e.g., DeepSeek‑R1 of 671 B params) ([datacamp.com][3]).
* **Tool-use and function calling**: Built to interact with external tools and manage agentic workflows—outperforming models like o1‑mini in the Berkeley Function Calling leaderboard ([groq.com][4]).
* **Self-reflective reasoning (“chain-of-thought”)**: Internally uses RL to pause and reflect (“<think>…”) before producing answers, enhancing accuracy despite verbose outputs ([groq.com][4]).

---

### 🛠️ Training & Access

* **Built by Alibaba Cloud's Qwen team**: Based on pre‑training Qwen 2.5‑32B, then RL‑finetuned for reasoning tasks using verifiers for math and code correctness ([qwenlm.github.io][5]).
* **Open-source**: Released under the Apache 2.0 license, available via Hugging Face and ModelScope, and accessible through Qwen Chat ([alibabacloud.com][6]).
* **Deployment support**: Available on platforms like Groq Cloud and SambaNova, offering high-speed inference (e.g., \~400 tokens/sec at competitive pricing) ([groq.com][4]).

---

### 🌐 Who built it?

* **Developer**: **Alibaba Cloud** (Qwen team)
* **Part of**: The Qwen LLM family—a growing open-source series from Alibaba, with Qwen3 being the latest ([en.wikipedia.org][7], [arxiv.org][8]).

---

### 🔍 Summary Table

| Feature            | Details                                                 |
| ------------------ | ------------------------------------------------------- |
| **Parameters**     | \~32 B                                                  |
| **Architecture**   | Transformer with RoPE, SwiGLU, RMSNorm, QKV bias        |
| **Context window** | Up to 131K tokens                                       |
| **Strengths**      | Reasoning, math, code, tool use                         |
| **Benchmarks**     | Comparable to much larger models (DeepSeek-R1, o1-mini) |
| **Access**         | Open-source (Apache 2.0); hosted on multiple platforms  |
| **Built by**       | Alibaba Cloud’s Qwen team                               |

---

In essence, **QwQ‑32B** is a mid-sized, open-source reasoning powerhouse from Alibaba—delivering sophisticated analytical performance while remaining efficient and accessible.

* [barrons.com](https://www.barrons.com/articles/alibaba-baba-stock-adr-price-qwen-deepseek-064f5fcc?utm_source=chatgpt.com)
* [time.com](https://time.com/7265415/alibaba-model-ai-china-deepseek/?utm_source=chatgpt.com)
* [reuters.com](https://www.reuters.com/technology/alibaba-shares-surge-after-it-unveils-reasoning-model-2025-03-06/?utm_source=chatgpt.com)

[1]: https://medium.com/%40ferreradaniel/power-of-ai-reasoning-qwen-qwq-32b-revolutionizes-problem-solving-8c775607826f?utm_source=chatgpt.com "Power of AI Reasoning: Qwen QwQ-32B Revolutionizes Problem ..."
[2]: https://huggingface.co/Qwen/QwQ-32B?utm_source=chatgpt.com "Qwen/QwQ-32B - Hugging Face"
[3]: https://www.datacamp.com/blog/qwq-32b?utm_source=chatgpt.com "QwQ-32B: Features, Access, DeepSeek-R1 Comparison & More"
[4]: https://groq.com/a-guide-to-reasoning-with-qwen-qwq-32b/?utm_source=chatgpt.com "A Guide to Reasoning with Qwen QwQ 32B - Groq is Fast AI Inference"
[5]: https://qwenlm.github.io/blog/qwq-32b/?utm_source=chatgpt.com "QwQ-32B: Embracing the Power of Reinforcement Learning - Qwen"
[6]: https://www.alibabacloud.com/blog/alibaba-cloud-unveils-qwq-32b-a-compact-reasoning-model-with-cutting-edge-performance_602039?utm_source=chatgpt.com "Alibaba Cloud Unveils QwQ-32B: A Compact Reasoning Model with ..."
[7]: https://en.wikipedia.org/wiki/Qwen?utm_source=chatgpt.com "Qwen"
[8]: https://arxiv.org/abs/2505.09388?utm_source=chatgpt.com "Qwen3 Technical Report"


## Langchain chat prompt template

In [57]:
### Prompt Engineering
from langchain_core.prompts import ChatPromptTemplate

prompt=ChatPromptTemplate.from_messages(
    [
        ("system","You are an expert AI Engineer. Provide me answer based on the question"),
        ("user","{input}")
    ]
)
prompt

ChatPromptTemplate(input_variables=['input'], input_types={}, partial_variables={}, messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You are an expert AI Engineer. Provide me answer based on the question'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['input'], input_types={}, partial_variables={}, template='{input}'), additional_kwargs={})])

In [58]:
from langchain_groq import ChatGroq
model=ChatGroq(model="gemma2-9b-it")
model

ChatGroq(client=<groq.resources.chat.completions.Completions object at 0x0000017551419650>, async_client=<groq.resources.chat.completions.AsyncCompletions object at 0x000001755141A1D0>, model_name='gemma2-9b-it', model_kwargs={}, groq_api_key=SecretStr('**********'))

> gemma2-9b-it

**Gemma 2 9B‑IT** is the instruction-tuned, text-generation-focused variant of Google’s open-source Gemma 2 model series. Here's a breakdown of what makes it special:

---

### 🧠 What is Gemma 2 9B-IT?

* **Text-to-text, decoder‑only LLM**: Based on the same research and architecture as Google's Gemini models and fine-tuned for instruction-following tasks like chat, summarization, code generation, reasoning, and more ([huggingface.co][1]).
* **Mid-sized (\~9 billion parameters)**: Offers a strong balance between performance and computational efficiency — outperforming models like Llama 3 8B in its category ([blog.google][2]).
* **Core design improvements**: Utilizes advanced techniques like group-query attention, extra RMSNorm layers, and distillation from larger variants to boost performance and stability ([developers.googleblog.com][3]).
* **Context window**: Typically supports around 8K tokens (as part of the Gemma 2 family), although future variants (Gemma 3) expand this ([docsbot.ai][4]).

---

### ⚙️ Capabilities & Usage

* **Instruction-tuned** (“IT”): Specialized to follow user instructions, making it excellent for chatbots, content creation, Q\&A, and language transformation.
* **Versatile applications**: Works well for text generation (stories, essays), summarization, translation, basic code generation and reasoning, and more ([build.nvidia.com][5]).
* **Developer-friendly**: Open weights under Google’s Gemma license, usable via Hugging Face, NVIDIA NIM containers, Ollama, OpenRouter, DeepInfra, etc. ([huggingface.co][1]).
* **Hardware-friendly**: Efficient enough to run inference on GPUs (e.g., A100/H100 or even home hardware setups) and via on-device frameworks like Gemma.cpp or llama.cpp ([huggingface.co][6]).

---

### 🌐 Who built it?

* **Developed by**: Google (Gemma Team / Google DeepMind), as part of the Gemma 2 model family ([huggingface.co][1]).
* **Instruction-tuned variant**: The “IT” suffix indicates fine-tuning on conversational and instructional datasets to optimize behavior in chat and command-following scenarios.

---

### 🧪 Community Impressions

On Reddit (r/LocalLLaMA), users praise its performance and personality:

> “This is the best model I have ever run on my 3060 shit‑box… It’s the first model that genuinely felt better than GPT‑3.5.” ([developers.googleblog.com][7], [reddit.com][8])

They highlight its friendly tone, multilingual capabilities, and strong suitability for roleplay — albeit with occasional factual inaccuracies ([reddit.com][8]).

---

### 📋 Quick Overview

| Feature            | Details                                                                               |
| ------------------ | ------------------------------------------------------------------------------------- |
| **Params**         | \~9 billion                                                                           |
| **Architecture**   | Gemma 2 backbone; instruction‑tuned                                                   |
| **Context window** | \~8K tokens                                                                           |
| **Strengths**      | Efficient inference, instruction-following, multilingual writing, creative generation |
| **Usage**          | Chatbots, summarization, code, general text                                           |
| **Access**         | Open-source on Hugging Face, NVIDIA NIM, Ollama, DeepInfra, etc.                      |
| **Developer**      | Google / DeepMind Gemma Team                                                          |

---

**In summary:**
Gemma 2 9B‑IT is a highly capable, efficient, instruction‑tuned language model from Google. It's optimized for chat and content generation tasks within a practical 9B parameter size, offering open access for developers and strong performance relative to similarly sized models.

Feel free to ask if you want usage examples, benchmarks, or deployment pointers!

[1]: https://huggingface.co/google/gemma-2-9b-it?utm_source=chatgpt.com "google/gemma-2-9b-it - Hugging Face"
[2]: https://blog.google/technology/developers/google-gemma-2/?utm_source=chatgpt.com "Gemma 2 is now available to researchers and developers"
[3]: https://developers.googleblog.com/gemma-explained-new-in-gemma-2?utm_source=chatgpt.com "Gemma explained: What's new in Gemma 2 - Google Developers Blog"
[4]: https://docsbot.ai/models/gemma-2-9b?utm_source=chatgpt.com "Google's Gemma 2 9B - AI Model Details - DocsBot AI"
[5]: https://build.nvidia.com/google/gemma-2-9b-it/modelcard?utm_source=chatgpt.com "gemma-2-9b-it Model by Google | NVIDIA NIM"
[6]: https://huggingface.co/INSAIT-Institute/BgGPT-Gemma-2-9B-IT-v1.0?utm_source=chatgpt.com "INSAIT-Institute/BgGPT-Gemma-2-9B-IT-v1.0 - Hugging Face"
[7]: https://developers.googleblog.com/en/gemma-explained-overview-gemma-model-family-architectures/?utm_source=chatgpt.com "Gemma explained: An overview of Gemma model family architectures"
[8]: https://www.reddit.com/r/LocalLLaMA/comments/1drxhlh/gemma_2_9b_appreciation_post/?utm_source=chatgpt.com "Gemma 2 9b appreciation post : r/LocalLLaMA - Reddit"
 

## chaining

In [59]:
chain=prompt|model
chain

ChatPromptTemplate(input_variables=['input'], input_types={}, partial_variables={}, messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You are an expert AI Engineer. Provide me answer based on the question'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['input'], input_types={}, partial_variables={}, template='{input}'), additional_kwargs={})])
| ChatGroq(client=<groq.resources.chat.completions.Completions object at 0x0000017551419650>, async_client=<groq.resources.chat.completions.AsyncCompletions object at 0x000001755141A1D0>, model_name='gemma2-9b-it', model_kwargs={}, groq_api_key=SecretStr('**********'))

In [60]:
response=chain.invoke({"input":"Can you tell me something about Langsmith"})
print(response.content)

You're asking about **Langsmith**, which is a really interesting project in the AI world! 

Here's what I can tell you as an AI Engineer:

**Langsmith is an open-source platform designed for developing and deploying AI agents.**

Think of it like a toolkit specifically built for creating intelligent programs that can understand and respond to natural language. It's built on top of powerful language models like OpenAI's GPT and aims to make it easier for developers to build sophisticated AI applications.

**Here are some key features of Langsmith:**

* **Modular Design:** It allows you to break down complex AI agents into smaller, manageable modules, making development and maintenance more efficient.

* **Agent Orchestration:** Langsmith helps you connect and coordinate different AI modules to create more complex and capable agents.

* **Fine-Tuning Capabilities:** You can fine-tune existing language models on your specific datasets, leading to more accurate and relevant responses for y

## Langchain Output Parser

### StrOutputParser

In [61]:
### OutputParser
from langchain_core.output_parsers import StrOutputParser

output_parser=StrOutputParser()

chain=prompt|model|output_parser

response=chain.invoke({"input":"Can you tell me about Langsmith"})
print(response)

Let's talk about Langsmith!

Langsmith is a powerful open-source platform developed by the brilliant minds at Weights & Biases. It's designed specifically to streamline and simplify the process of building, training, and deploying large language models (LLMs). 

Here's a breakdown of its key features and what makes it so exciting:

**1. Simplifying LLM Development:**

* **Modular Design:** Langsmith breaks down the LLM development workflow into manageable modules. This makes it easier to understand, customize, and iterate on different aspects of your project.

* **Easy Experimentation:**  It offers a streamlined interface for running experiments with various model architectures, training parameters, and datasets. This accelerates the process of finding the best configurations for your specific needs.

* **Code Generation:** Langsmith can help you generate code for common LLM tasks, saving you time and reducing boilerplate.

**2. Powerful Training Capabilities:**

* **GPU Acceleration:*

### JsonOutputParser

In [62]:
from langchain_core.output_parsers import JsonOutputParser

output_parser=JsonOutputParser()
output_parser.get_format_instructions()

'Return a JSON object.'

In [63]:
### OutputParser
from langchain_core.output_parsers import JsonOutputParser
from langchain_core.prompts import PromptTemplate

output_parser=JsonOutputParser()

prompt=PromptTemplate(
    template="Answer the user query \n {format_instruction}\n {query}\n ",
    input_variables=["query"],
    partial_variables={"format_instruction":output_parser.get_format_instructions()},
)

In [64]:
prompt


PromptTemplate(input_variables=['query'], input_types={}, partial_variables={'format_instruction': 'Return a JSON object.'}, template='Answer the user query \n {format_instruction}\n {query}\n ')

In [65]:
chain=prompt|model|output_parser
response=chain.invoke({"query":"Can you tell me about Langsmith?"})
print(response)

{'name': 'Langsmith', 'description': 'Langsmith is an open-source platform for building and deploying AI assistants.', 'features': ['Modular design allows for customization and extensibility', 'Built-in support for various AI models, including open-source options', 'Easy-to-use interface for creating and managing AI assistants', 'Tools for training and fine-tuning AI models', 'Deployment options for both cloud and on-premise environments', 'Focus on privacy and security'], 'website': 'https://www.langsmith.com/'}


In [66]:
from pprint import pprint
pprint(response['description'])

'Langsmith is an open-source platform for building and deploying AI assistants.'


In [67]:
from langchain_core.prompts import ChatPromptTemplate

prompt=ChatPromptTemplate.from_messages(
    [
        ("system","You are an expert AI Engineer.Provide the response in json.Provide me answer based on the question"),
        ("user","{input}")
    ]
)
prompt

ChatPromptTemplate(input_variables=['input'], input_types={}, partial_variables={}, messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You are an expert AI Engineer.Provide the response in json.Provide me answer based on the question'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['input'], input_types={}, partial_variables={}, template='{input}'), additional_kwargs={})])

In [68]:
chain=prompt|model|output_parser
response=chain.invoke({"input":"Can you tell me about Langsmith?"})
print(response)

{'answer': 'LangSmith is an open-source tool developed by Replicate that aims to simplify the process of fine-tuning large language models (LLMs). It provides a user-friendly interface and a streamlined workflow for customizing LLMs to specific tasks or domains.\n\nHere are some key features of LangSmith:\n\n* **Ease of Use:** LangSmith is designed to be accessible to both technical and non-technical users. Its intuitive interface makes it easier to understand and navigate the fine-tuning process.\n* **Data-Centric Approach:** LangSmith emphasizes the importance of high-quality training data. It offers tools for data preparation, cleaning, and annotation, ensuring that LLMs are trained on relevant and accurate information.\n* **Model Selection and Customization:** LangSmith supports a variety of pre-trained LLMs from different providers, allowing users to choose the model that best suits their needs. It also enables fine-tuning these models with custom datasets.\n* **Experiment Trackin

In [69]:
pprint(response)

{'answer': 'LangSmith is an open-source tool developed by Replicate that aims '
           'to simplify the process of fine-tuning large language models '
           '(LLMs). It provides a user-friendly interface and a streamlined '
           'workflow for customizing LLMs to specific tasks or domains.\n'
           '\n'
           'Here are some key features of LangSmith:\n'
           '\n'
           '* **Ease of Use:** LangSmith is designed to be accessible to both '
           'technical and non-technical users. Its intuitive interface makes '
           'it easier to understand and navigate the fine-tuning process.\n'
           '* **Data-Centric Approach:** LangSmith emphasizes the importance '
           'of high-quality training data. It offers tools for data '
           'preparation, cleaning, and annotation, ensuring that LLMs are '
           'trained on relevant and accurate information.\n'
           '* **Model Selection and Customization:** LangSmith supports a '
      

### XML output parser

In [70]:
### OutputParser
from langchain_core.output_parsers import XMLOutputParser
output_parser=XMLOutputParser()
from langchain_core.prompts import ChatPromptTemplate

prompt=ChatPromptTemplate.from_messages(
    [
        ("system","You are an expert AI Engineer.<response><answer>Your answer here</answer></response>.Provide me answer based on the question"),
        ("user","{input}")
    ]
)
prompt

ChatPromptTemplate(input_variables=['input'], input_types={}, partial_variables={}, messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You are an expert AI Engineer.<response><answer>Your answer here</answer></response>.Provide me answer based on the question'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['input'], input_types={}, partial_variables={}, template='{input}'), additional_kwargs={})])

In [71]:
### OutputParser
from langchain_core.output_parsers import XMLOutputParser
from langchain_core.prompts import PromptTemplate

output_parser=XMLOutputParser()

prompt=PromptTemplate(
    template="Answer the user query \n {format_instruction}\n {query}\n ",
    input_variables=["query"],
    partial_variables={"format_instruction":output_parser.get_format_instructions()},
)
prompt

PromptTemplate(input_variables=['query'], input_types={}, partial_variables={'format_instruction': 'The output should be formatted as a XML file.\n1. Output should conform to the tags below.\n2. If tags are not given, make them on your own.\n3. Remember to always open and close all the tags.\n\nAs an example, for the tags ["foo", "bar", "baz"]:\n1. String "<foo>\n   <bar>\n      <baz></baz>\n   </bar>\n</foo>" is a well-formatted instance of the schema.\n2. String "<foo>\n   <bar>\n   </foo>" is a badly-formatted instance.\n3. String "<foo>\n   <tag>\n   </tag>\n</foo>" is a badly-formatted instance.\n\nHere are the output tags:\n```\nNone\n```'}, template='Answer the user query \n {format_instruction}\n {query}\n ')

In [72]:
chain=prompt|model
response=chain.invoke({"query":"Can you tell me about Langsmith?"})
print(response)

content='<?xml version="1.0" encoding="UTF-8"?>\n<langsmith_info>\n  <description>Langsmith is an open-source platform developed by AI21 Labs for building and deploying large language models (LLMs). It provides a comprehensive suite of tools and resources for the entire LLM lifecycle, from training and fine-tuning to deployment and monitoring.</description>\n  <features>\n    <feature>Modular and customizable architecture</feature>\n    <feature>Support for various LLM architectures and training methods</feature>\n    <feature>Integrated tools for data preprocessing, model evaluation, and debugging</feature>\n    <feature>Cloud-based deployment options for scalable and efficient inference</feature>\n  </features>\n  <purpose>\n    <para>Langsmith aims to democratize access to LLM technology by empowering developers and researchers with the tools and infrastructure they need to build and deploy cutting-edge AI applications.</para>\n  </purpose>\n</langsmith_info> \n' additional_kwargs={

In [73]:
pprint(response.content)

('<?xml version="1.0" encoding="UTF-8"?>\n'
 '<langsmith_info>\n'
 '  <description>Langsmith is an open-source platform developed by AI21 Labs '
 'for building and deploying large language models (LLMs). It provides a '
 'comprehensive suite of tools and resources for the entire LLM lifecycle, '
 'from training and fine-tuning to deployment and monitoring.</description>\n'
 '  <features>\n'
 '    <feature>Modular and customizable architecture</feature>\n'
 '    <feature>Support for various LLM architectures and training '
 'methods</feature>\n'
 '    <feature>Integrated tools for data preprocessing, model evaluation, and '
 'debugging</feature>\n'
 '    <feature>Cloud-based deployment options for scalable and efficient '
 'inference</feature>\n'
 '  </features>\n'
 '  <purpose>\n'
 '    <para>Langsmith aims to democratize access to LLM technology by '
 'empowering developers and researchers with the tools and infrastructure they '
 'need to build and deploy cutting-edge AI applications

In [74]:
##output parser
#from langchain_core.output_parsers import XMLOutputParser
from langchain.output_parsers.xml import XMLOutputParser

# XML Output Parser
output_parser = XMLOutputParser()

# Prompt that instructs the model to return XML
prompt = ChatPromptTemplate.from_messages([
    ("system", "You are a helpful assistant. Respond in this XML format: <response><answer>Your answer here</answer></response>"),
    ("human", "{input}")
])

# Build the chain
chain = prompt | model

# Run the chain
#response = chain.invoke({"input": "What is LangChain?"})

raw_output =chain.invoke({"input": "What is LangChain?"})

# Print result
print(raw_output)


content='<response><answer>LangChain is a framework for developing applications powered by large language models (LLMs). It provides tools and building blocks for tasks such as prompting, memory management, chaining together different LLMs, and integrating with external data sources.</answer></response> \n' additional_kwargs={} response_metadata={'token_usage': {'completion_tokens': 58, 'prompt_tokens': 39, 'total_tokens': 97, 'completion_time': 0.105454545, 'prompt_time': 0.002501304, 'queue_time': 0.23986750499999998, 'total_time': 0.107955849}, 'model_name': 'gemma2-9b-it', 'system_fingerprint': 'fp_10c08bf97d', 'finish_reason': 'stop', 'logprobs': None} id='run--6bbbe9dd-dd31-411d-9135-84f208cd4a6d-0' usage_metadata={'input_tokens': 39, 'output_tokens': 58, 'total_tokens': 97}


### Custom output parsing by Pydantic

In [75]:
## With Pydantic
from langchain_core.output_parsers import JsonOutputParser
from langchain_core.prompts import PromptTemplate
from langchain_openai import ChatOpenAI
from pydantic import BaseModel, Field

model = ChatOpenAI(temperature=0.7)


# Define your desired data structure.
class Joke(BaseModel):
    setup: str = Field(description="question to set up a joke")
    punchline: str = Field(description="answer to resolve the joke")


# And a query intented to prompt a language model to populate the data structure.
joke_query = "Tell me a joke."

# Set up a parser + inject instructions into the prompt template.
parser = JsonOutputParser(pydantic_object=Joke)

prompt = PromptTemplate(
    template="Answer the user query.\n{format_instructions}\n{query}\n",
    input_variables=["query"],
    partial_variables={"format_instructions": parser.get_format_instructions()},
)

chain = prompt | model | parser

chain.invoke({"query": joke_query})

{'setup': "Why couldn't the bicycle stand up by itself?",
 'punchline': 'It was two tired.'}

In [76]:
### Without Pydantic
joke_query = "Tell me a joke ."

parser = JsonOutputParser()

prompt = PromptTemplate(
    template="Answer the user query.\n{format_instructions}\n{query}\n",
    input_variables=["query"],
    partial_variables={"format_instructions": parser.get_format_instructions()},
)
chain = prompt | model | parser

chain.invoke({"query": joke_query})

{'joke': "Why couldn't the bicycle stand up by itself? Because it was two tired!"}

pydantic is helpful in JSON output parser to get required format

In [77]:

from langchain_core.output_parsers import XMLOutputParser
from langchain_core.prompts import PromptTemplate


actor_query = "Generate the shortened filmography for Tom Hanks."

output = model.invoke(
    f"""{actor_query}
Please enclose the movies in <movie></movie> tags"""
)

print(output.content)

<movie>Big</movie>
<movie>Saving Private Ryan</movie>
<movie>Forrest Gump</movie>
<movie>Cast Away</movie>
<movie>Apollo 13</movie>


In [78]:
from langchain.output_parsers import YamlOutputParser
from langchain_core.prompts import PromptTemplate
from langchain_openai import ChatOpenAI
from pydantic import BaseModel, Field


# Define your desired data structure.
class Joke(BaseModel):
    setup: str = Field(description="question to set up a joke")
    punchline: str = Field(description="answer to resolve the joke")


model = ChatOpenAI(temperature=0.5)

# And a query intented to prompt a language model to populate the data structure.
joke_query = "Tell me a joke."

# Set up a parser + inject instructions into the prompt template.
parser = YamlOutputParser(pydantic_object=Joke)

prompt = PromptTemplate(
    template="Answer the user query.\n{format_instructions}\n{query}\n",
    input_variables=["query"],
    partial_variables={"format_instructions": parser.get_format_instructions()},
)

chain = prompt | model | parser

chain.invoke({"query": joke_query})

Joke(setup="Why couldn't the bicycle find its way home?", punchline='Because it lost its bearings!')

## Assigments: https://python.langchain.com/docs/how_to/#prompt-templates

Here's a **comprehensive summary** of **all types of prompt templates in LangChain**, covering:

* 📌 Classes from your **uploaded image**
* 📌 Examples and use-cases
* 📌 Concepts from the linked guides:

  * Few-shot examples
  * Chat format examples
  * Partial prompts
  * Prompt composition
  * Multimodal prompts

---

#### 🧠 1. **BasePromptTemplate**

* **Abstract base** class for all prompt templates.
* Others like `PromptTemplate`, `ChatPromptTemplate` inherit from this.

---

#### 📄 2. **PromptTemplate**

* For **simple string-based** prompts.

```python
from langchain_core.prompts import PromptTemplate
template = PromptTemplate.from_template("Tell me a joke about {topic}")
print(template.format(topic="dogs"))
```

---

#### 🧵 3. **StringPromptTemplate**

* Same as `PromptTemplate`, but explicitly focuses on templates with `.format()` method exposure.

---

#### 💬 4. **ChatPromptTemplate**

* Structured prompt for chat models.

```python
from langchain_core.prompts import ChatPromptTemplate
chat_prompt = ChatPromptTemplate.from_messages([
    ("system", "You are a helpful assistant."),
    ("user", "What is the capital of {country}?")
])
chat_prompt.format(country="France")
```

---

#### 👤 5. **HumanMessagePromptTemplate**

* Message from the **user** in chat.

```python
from langchain_core.prompts import HumanMessagePromptTemplate
HumanMessagePromptTemplate.from_template("Translate {text} to Hindi.")
```

---

#### 🤖 6. **AIMessagePromptTemplate**

* Message from the **assistant/AI** in a chat.

```python
from langchain_core.prompts import AIMessagePromptTemplate
AIMessagePromptTemplate.from_template("Sure! Here is the translation.")
```

---

#### 🛠 7. **SystemMessagePromptTemplate**

* System-level instruction in a chat.

```python
from langchain_core.prompts import SystemMessagePromptTemplate
SystemMessagePromptTemplate.from_template("You are a scientific research assistant.")
```

---

#### 🔁 8. **ChatMessagePromptTemplate**

* Generic chat message with role (human, AI, system, function).

```python
ChatMessagePromptTemplate.from_template(role="function", template="Function name: {name}")
```

---

#### 🧱 9. **BaseChatPromptTemplate, BaseMessagePromptTemplate, BaseStringMessagePromptTemplate**

* Abstract base classes. Used internally for inheritance and consistency across chat/message templates.

---

#### 🔄 10. **MessagesPlaceholder**

* Used to inject a **list of existing messages** into a prompt dynamically.

```python
from langchain_core.prompts import MessagesPlaceholder
MessagesPlaceholder(variable_name="chat_history")
```

---

#### ✨ 11. **FewShotPromptTemplate**

* For **few-shot learning** in **string-based** prompts.

```python
from langchain_core.prompts import FewShotPromptTemplate, PromptTemplate
example_prompt = PromptTemplate.from_template("Q: {question}\nA: {answer}")
examples = [{"question": "2+2", "answer": "4"}, {"question": "3+5", "answer": "8"}]

prompt = FewShotPromptTemplate(
    examples=examples,
    example_prompt=example_prompt,
    suffix="Q: {input}\nA:",
    input_variables=["input"]
)
print(prompt.format(input="6+7"))
```

---

#### 💬✨ 12. **FewShotChatMessagePromptTemplate**

* Few-shot for **chat-based prompts**.

```python
from langchain_core.prompts import FewShotChatMessagePromptTemplate, ChatPromptTemplate
example_prompt = ChatPromptTemplate.from_messages([
    ("human", "{input}"),
    ("ai", "{output}")
])
examples = [{"input": "Hi", "output": "Hello!"}]

fewshot = FewShotChatMessagePromptTemplate(
    example_prompt=example_prompt,
    examples=examples
)
final_prompt = ChatPromptTemplate.from_messages([
    ("system", "Be friendly."),
    fewshot,
    ("human", "How are you?")
])
print(final_prompt.format(input="How are you?"))
```

---

#### 🧩 13. **FewShotPromptWithTemplates**

* A variant combining **few-shot logic** with multiple templates dynamically.
* Used when templates are complex or structured.

---

#### 🎥 14. **ImagePromptTemplate**

* For **multimodal models** (image + text).

```python
ChatPromptTemplate.from_messages([
    ("system", "Describe the image"),
    ("user", [{"type": "image_url", "url": "{image_url}"}])
])
```

---

#### 🔗 15. **PipelinePromptTemplate**

* Combines multiple prompt templates in a **pipeline**.

```python
from langchain_core.prompts import PipelinePromptTemplate
PipelinePromptTemplate(
    final_prompt=PromptTemplate.from_template("Q: {question}\nA:"),
    pipeline_prompts=[
        ("question", PromptTemplate.from_template("Summarize: {text}"))
    ]
)
```

---

#### 🧱 16. **StructuredPrompt**

* Represents structured formats, often used with output parsers or schemas.

---

### 🔁 Partial Prompts – \[Docs Summary]

* Fill some variables now, others later.
* Great for **dynamic chaining** and **reuse**.

---

### 🔧 Prompt Composition – \[Docs Summary]

* Combine strings or message templates via `+` operator or `extend()`.
* Encourages **modular prompt building**.

---

### 🖼 Multimodal Prompts – \[Docs Summary]

* Allow embedding **images, audio, PDFs** inside prompts.
* Works only with **multimodal models** like GPT-4V or Gemini.

---

### ✅ Summary Table

| Template                           | Input Style       | Best For                         |
| ---------------------------------- | ----------------- | -------------------------------- |
| `PromptTemplate`                   | String            | Simple instructions              |
| `ChatPromptTemplate`               | Messages          | Chatbots or assistants           |
| `FewShotPromptTemplate`            | String + Examples | Improve learning via demos       |
| `FewShotChatMessagePromptTemplate` | Chat + Examples   | Chat-style examples              |
| `MessagesPlaceholder`              | List Injection    | Adding existing message history  |
| `ImagePromptTemplate`              | Media block       | Multimodal inputs (images/audio) |
| `PipelinePromptTemplate`           | Modular pipeline  | Building chained prompts         |
| `PartialPrompt`                    | Partial values    | Dynamic reuse                    |
| `StructuredPrompt`                 | Structured output | Controlled formatting            |

---

Would you like a visual diagram (e.g. mindmap or table image) showing relationships and use cases for each class?


## Different types of Output parsers

Here’s a comprehensive overview of **all built‑in output parser types in LangChain**, with clear explanations, examples, and when to use each:

---

### 📦 Output Parser Types

([python.langchain.com][1])

#### 1. **StringOutputParser**

* **Purpose**: Normalizes LLM or Chat output into a plain Python string.
* **Example**:

  ```python
  from langchain_core.output_parsers import StringOutputParser
  parser = StringOutputParser()
  parser.parse("Hello, world!")  # => "Hello, world!"
  ```

---

#### 2. **JSON (JsonOutputParser or PydanticParser)**

* **Purpose**: Extracts structured JSON using optional Pydantic validation.
* **Example**:

  ````python
  from langchain_core.output_parsers import JsonOutputParser
  from langchain_core.pydantic_v1 import BaseModel, Field

  class Joke(BaseModel):
      setup: str
      punchline: str

  parser = JsonOutputParser(pydantic_object=Joke)
  instructions = parser.get_format_instructions()
  # Include `instructions` in prompt...
  result = parser.parse(response_text)
  # => {'setup': "...", 'punchline': "..."}
  ``` :contentReference[oaicite:4]{index=4}
  ````

---

#### 3. **YAML OutputParser**

* **Purpose**: Outputs validated structured data in YAML format using Pydantic.
* Use `JsonOutputParser(..., mode="yaml")` or `YAMLOutputParser`.

---

#### 4. **XML Parser**

* **Purpose**: Parses XML-formatted strings into Python `dict`.
* Use when dealing with XML-based tool formats. ([reddit.com][2], [python.langchain.com][1])

---

#### 5. **CSV Parser (CommaSeparatedListOutputParser)**

* **Purpose**: Converts comma-separated LLM output into a `List[str]`.
* **Example**:

  ````python
  from langchain.output_parsers import CommaSeparatedListOutputParser
  parser = CommaSeparatedListOutputParser()
  instructions = parser.get_format_instructions()
  # Prompt: "List fruits: …{instructions}"
  result = parser.parse("Apple, Banana, Cherry")
  # => ["Apple", "Banana", "Cherry"]
  ``` :contentReference[oaicite:11]{index=11}
  ````

---

#### 6. **EnumOutputParser**

* **Purpose**: Ensures output matches one value from a given Python `Enum`.
* Use when only specific categorical responses are valid. ([python.langchain.com][3])

---

#### 7. **DatetimeOutputParser**

* **Purpose**: Parses output into a Python `datetime.datetime`.
* **Example**:

  ````python
  from langchain.output_parsers import DatetimeOutputParser
  parser = DatetimeOutputParser()
  # Use parser.get_format_instructions() in prompt
  parser.parse("1991-02-20 00:00:00")
  # => datetime.datetime(1991, 2, 20)
  ``` :contentReference[oaicite:16]{index=16}
  ````

---

#### 8. **PandasDataFrame Parser**

* **Purpose**: Outputs structured tabular data as a pandas DataFrame.
* Great for spreadsheet-style outputs. ([python.langchain.com][4], [python.langchain.com][1])

---

#### 9. **StructuredOutputParser**

* **Purpose**: Generates `Dict[str, str]` with predefined keys only—lighter weight than JSON/YAML.
* **Example**:

  ````python
  from langchain.output_parsers import StructuredOutputParser
  parser = StructuredOutputParser.from_names_and_descriptions({
      "meaning": "detailed meaning of the expression"
  })
  instructions = parser.get_format_instructions()
  # Include in chat prompt...
  parser.parse(response_text)
  # => {"meaning": "..."}
  ``` :contentReference[oaicite:21]{index=21}
  ````

---

#### 10. **OutputFixingParser & RetryWithErrorParser**

* **Purpose**: Wrap another parser; on failure, invoke the LLM to:

  * *OutputFixingParser*: fix just the failed output.
  * *RetryWithErrorParser*: retry with full context.
* Useful for making parsing more robust. ([python.langchain.com][1])

---

#### 11. **OpenAIFunctions & OpenAITools Parsers**

* **Purpose**: Use native OpenAI (or tools) function-calling protocol to get structured outputs.
* **Example**:

  ```python
  from langchain.output_parsers import OpenAIFunctionsOutputParser
  parser = OpenAIFunctionsOutputParser(functions=...)
  # Use this with ChatOpenAI(..., functions=...)
  ```
* Recommended when using GPT models supporting function calls. ([python.langchain.com][4])

---

### 🧰 Custom Parsers

* **BaseOutputParser** or **BaseGenerationOutputParser**: for complex or bespoke formats.
* **Example**: Boolean parser converting `"YES"/"NO"` to `bool` ([python.langchain.com][3])

---

### ✅ Summary Table

| Parser Type                | Output Type              | Use Case                                |
| -------------------------- | ------------------------ | --------------------------------------- |
| StringOutputParser         | `str`                    | Normalize raw outputs                   |
| JsonOutputParser           | `dict` or Pydantic model | Structured JSON data                    |
| YAMLOutputParser           | Pydantic model via YAML  | Human‑friendly structured data          |
| XML Parser                 | `dict`                   | XML output parsing                      |
| CSV Parser                 | `List[str]`              | CSV‑style lists                         |
| EnumOutputParser           | Enum                     | Categorical single‑choice responses     |
| DatetimeOutputParser       | `datetime.datetime`      | Date/time extraction                    |
| PandasDataFrame Parser     | `pd.DataFrame` or `dict` | Tabular data analysis                   |
| StructuredOutputParser     | `Dict[str, str]`         | Lightweight structured responses        |
| OutputFixing/Retry Parsers | Wrapped another parser   | Enhanced parsing reliability            |
| OpenAIFunctions/Tools      | JSON object              | Use native function‑calling support     |
| Custom Parsers             | Any Python type          | Special formats and raw output handling |

---

### 🔗 Best Practices

* Use **native function-call parsers** (OpenAIFunctions/OpenAITools) if available for guaranteed structured output.
* Otherwise, choose **JSON/YAML** with Pydantic for robustness.
* Use **CSV, Enum, Datetime** for simpler, common data types.
* Add **Fixing/Retry wrappers** to handle parsing errors gracefully.
* Create **custom parsers** when facing unique output formats.

---

Let me know if you'd like example chains showcasing these parsers in action!

[1]: https://python.langchain.com/docs/concepts/output_parsers/?utm_source=chatgpt.com "Output parsers | 🦜️🔗 LangChain"
[2]: https://www.reddit.com/r/LangChain/comments/1fdxh8o?utm_source=chatgpt.com "PromptTemplate coupled to LLM parsing output"
[3]: https://python.langchain.com/v0.1/docs/modules/model_io/output_parsers/custom/?utm_source=chatgpt.com "Custom Output Parsers | 🦜️🔗 LangChain"
[4]: https://python.langchain.com/v0.1/docs/modules/model_io/output_parsers/?utm_source=chatgpt.com "Output Parsers | 🦜️🔗 LangChain"


## Assignment
Create a simple assistant that uses any LLM and should be pydantic, when we ask about any product it should give you two information product Name, product details tentative price in USD (integer). use chat Prompt Template.


In [85]:
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import PydanticOutputParser
from pydantic import BaseModel

# Step 1: Define Pydantic schema for structured output
class ProductInfo(BaseModel):
    name: str
    details: str
    price_usd: int

# Step 2: Initialize the parser
parser = PydanticOutputParser(pydantic_object=ProductInfo)

# Step 3: Define the prompt with format instructions
prompt = ChatPromptTemplate.from_messages([
    ("system", "You are a helpful assistant that provides product information."),
    ("human", "Give information about the following product: {product_query}\n{format_instructions}")
])
formatted_prompt = prompt.partial(format_instructions=parser.get_format_instructions())

# Step 4: Initialize the ChatGroq model
llm = ChatGroq(model="gemma2-9b-it")

# Step 5: Chain everything together
chain = formatted_prompt | llm | parser



In [86]:
query = input("Ask about a product: ")
try:
    response = chain.invoke({"product_query": query})
    print("\n--- Product Info ---")
    print(f"Name       : {response.name}")
    print(f"Details    : {response.details}")
    print(f"Price (USD): ${response.price_usd}")
except Exception as e:
    print("Error:", e)


--- Product Info ---
Name       : HP Victus 16
Details    : A gaming laptop with a 16.1-inch display, powerful processor, and dedicated graphics card.
Price (USD): $799


## Data Ingestion

In [87]:
### text loader
from langchain_community.document_loaders.text import TextLoader

### Text loader

In [88]:
loader=TextLoader('data\speech.txt')
loader

In [89]:
text_documents=loader.load()
text_documents

[Document(metadata={'source': 'data\\speech.txt'}, page_content='The world must be made safe for democracy. Its peace must be planted upon the tested foundations of political liberty. We have no selfish ends to serve. We desire no conquest, no dominion. We seek no indemnities for ourselves, no material compensation for the sacrifices we shall freely make. We are but one of the champions of the rights of mankind. We shall be satisfied when those rights have been made as secure as the faith and the freedom of nations can make them.\n\nJust because we fight without rancor and without selfish object, seeking nothing for ourselves but what we shall wish to share with all free peoples, we shall, I feel confident, conduct our operations as belligerents without passion and ourselves observe with proud punctilio the principles of right and of fair play we profess to be fighting for.\n\n…\n\nIt will be all the easier for us to conduct ourselves as belligerents in a high spirit of right and fairn

### Pdf loader

In [90]:
### Read a PDf file
from langchain_community.document_loaders import PyPDFLoader
loader=PyPDFLoader('data\syllabus.pdf')
docs=loader.load()
docs

[Document(metadata={'producer': 'Canva', 'creator': 'Canva', 'creationdate': '2025-01-30T20:27:03+00:00', 'title': 'Ultimate Data Science & GenAI Bootcamp', 'moddate': '2025-01-30T20:26:59+00:00', 'keywords': 'DAGdmhcqnYw,BAEmsmap8Lg,0', 'author': 'monal singh', 'containsaigeneratedcontent': 'Yes', 'source': 'data\\syllabus.pdf', 'total_pages': 34, 'page': 0, 'page_label': '1'}, page_content='MACHINE\nLEARNING\nDEEP\nLEARNING\nPYTHON +\nSTATS\nCOMPUTER VISIONNATURAL LANGUAGE PROCESSING\nGENERATIVE AI\nRETRIEVAL AUGUMENT GENERATION\nVECTOR DB'),
 Document(metadata={'producer': 'Canva', 'creator': 'Canva', 'creationdate': '2025-01-30T20:27:03+00:00', 'title': 'Ultimate Data Science & GenAI Bootcamp', 'moddate': '2025-01-30T20:26:59+00:00', 'keywords': 'DAGdmhcqnYw,BAEmsmap8Lg,0', 'author': 'monal singh', 'containsaigeneratedcontent': 'Yes', 'source': 'data\\syllabus.pdf', 'total_pages': 34, 'page': 1, 'page_label': '2'}, page_content='This course is designed for aspiring data scientists,

### Web base loader

In [91]:
## Web based loader
from langchain_community.document_loaders import WebBaseLoader
import bs4
loader=WebBaseLoader(web_paths=("https://python.langchain.com/docs/introduction/",),)
docs=loader.load()
docs

USER_AGENT environment variable not set, consider setting it to identify your requests.


[Document(metadata={'source': 'https://python.langchain.com/docs/introduction/', 'title': 'Introduction | \uf8ffü¶úÔ∏è\uf8ffüîó LangChain', 'description': 'LangChain is a framework for developing applications powered by large language models (LLMs).', 'language': 'en'}, page_content='\n\n\n\n\nIntroduction | \uf8ffü¶úÔ∏è\uf8ffüîó LangChain\n\n\n\n\n\n\nSkip to main contentWe are growing and hiring for multiple roles for LangChain, LangGraph and LangSmith.  Join our team!IntegrationsAPI ReferenceMoreContributingPeopleError referenceLangSmithLangGraphLangChain HubLangChain JS/TSv0.3v0.3v0.2v0.1\uf8ffüí¨SearchIntroductionTutorialsBuild a Question Answering application over a Graph DatabaseTutorialsBuild a simple LLM application with chat models and prompt templatesBuild a ChatbotBuild a Retrieval Augmented Generation (RAG) App: Part 2Build an Extraction ChainBuild an AgentTaggingBuild a Retrieval Augmented Generation (RAG) App: Part 1Build a semantic search engineBuild a Question/Answerin

In [92]:
print(docs[0].page_content)






Introduction | ü¶úÔ∏èüîó LangChain






Skip to main contentWe are growing and hiring for multiple roles for LangChain, LangGraph and LangSmith.  Join our team!IntegrationsAPI ReferenceMoreContributingPeopleError referenceLangSmithLangGraphLangChain HubLangChain JS/TSv0.3v0.3v0.2v0.1üí¨SearchIntroductionTutorialsBuild a Question Answering application over a Graph DatabaseTutorialsBuild a simple LLM application with chat models and prompt templatesBuild a ChatbotBuild a Retrieval Augmented Generation (RAG) App: Part 2Build an Extraction ChainBuild an AgentTaggingBuild a Retrieval Augmented Generation (RAG) App: Part 1Build a semantic search engineBuild a Question/Answering system over SQL dataSummarize TextHow-to guidesHow-to guidesHow to use tools in a chainHow to use a vectorstore as a retrieverHow to add memory to chatbotsHow to use example selectorsHow to add a semantic layer over graph databaseHow to invoke runnables in parallelHow to stream chat model responsesHow to add 

In [93]:
## Web based loader
from langchain_community.document_loaders import WebBaseLoader
import bs4
loader=WebBaseLoader(web_paths=("https://lilianweng.github.io/posts/2023-06-23-agent/",),
                     bs_kwargs=dict(parse_only=bs4.SoupStrainer(
                         class_=("post-title","post-content","post-header")
                     ))
                     )

doc=loader.load()
doc

[Document(metadata={'source': 'https://lilianweng.github.io/posts/2023-06-23-agent/'}, page_content='\n\n      LLM Powered Autonomous Agents\n    \nDate: June 23, 2023  |  Estimated Reading Time: 31 min  |  Author: Lilian Weng\n\n\nBuilding agents with LLM (large language model) as its core controller is a cool concept. Several proof-of-concepts demos, such as AutoGPT, GPT-Engineer and BabyAGI, serve as inspiring examples. The potentiality of LLM extends beyond generating well-written copies, stories, essays and programs; it can be framed as a powerful general problem solver.\nAgent System Overview#\nIn a LLM-powered autonomous agent system, LLM functions as the agent’s brain, complemented by several key components:\n\nPlanning\n\nSubgoal and decomposition: The agent breaks down large tasks into smaller, manageable subgoals, enabling efficient handling of complex tasks.\nReflection and refinement: The agent can do self-criticism and self-reflection over past actions, learn from mistake

In [94]:
## Web based loader
from langchain_community.document_loaders import WebBaseLoader
import bs4
loader=WebBaseLoader(web_paths=("https://lilianweng.github.io/posts/2023-06-23-agent/",),
                     bs_kwargs=dict(parse_only=bs4.SoupStrainer(
                         class_=("post-title")
                     ))
                     )

doc=loader.load()
doc

[Document(metadata={'source': 'https://lilianweng.github.io/posts/2023-06-23-agent/'}, page_content='\n      LLM Powered Autonomous Agents\n    ')]

In [95]:
print(doc[0].page_content)


      LLM Powered Autonomous Agents
    


In [96]:
print(doc[0].page_content)


      LLM Powered Autonomous Agents
    


### Arxiv Loader

In [97]:
#Arxiv
from langchain_community.document_loaders import ArxivLoader
docs = ArxivLoader(query="1706.03762", load_max_docs=2).load()
docs

[Document(metadata={'Published': '2023-08-02', 'Title': 'Attention Is All You Need', 'Authors': 'Ashish Vaswani, Noam Shazeer, Niki Parmar, Jakob Uszkoreit, Llion Jones, Aidan N. Gomez, Lukasz Kaiser, Illia Polosukhin', 'Summary': 'The dominant sequence transduction models are based on complex recurrent or\nconvolutional neural networks in an encoder-decoder configuration. The best\nperforming models also connect the encoder and decoder through an attention\nmechanism. We propose a new simple network architecture, the Transformer, based\nsolely on attention mechanisms, dispensing with recurrence and convolutions\nentirely. Experiments on two machine translation tasks show these models to be\nsuperior in quality while being more parallelizable and requiring significantly\nless time to train. Our model achieves 28.4 BLEU on the WMT 2014\nEnglish-to-German translation task, improving over the existing best results,\nincluding ensembles by over 2 BLEU. On the WMT 2014 English-to-French\ntr

In [98]:
len(docs)

1

In [99]:
#Arxiv
from langchain_community.document_loaders import ArxivLoader
docs = ArxivLoader(query="Attention is all you need", load_max_docs=2).load()
docs

[Document(metadata={'Published': '2024-07-22', 'Title': "Attention Is All You Need But You Don't Need All Of It For Inference of Large Language Models", 'Authors': 'Georgy Tyukin, Gbetondji J-S Dovonon, Jean Kaddour, Pasquale Minervini', 'Summary': 'The inference demand for LLMs has skyrocketed in recent months, and serving\nmodels with low latencies remains challenging due to the quadratic input length\ncomplexity of the attention layers. In this work, we investigate the effect of\ndropping MLP and attention layers at inference time on the performance of\nLlama-v2 models. We find that dropping dreeper attention layers only marginally\ndecreases performance but leads to the best speedups alongside dropping entire\nlayers. For example, removing 33\\% of attention layers in a 13B Llama2 model\nresults in a 1.8\\% drop in average performance over the OpenLLM benchmark. We\nalso observe that skipping layers except the latter layers reduces performances\nfor more layers skipped, except for 

### Wikipedia Loader

In [100]:
from langchain_community.document_loaders import WikipediaLoader
docs = WikipediaLoader(query="Generative AI", load_max_docs=4).load()
len(docs)
print(docs)

[Document(metadata={'title': 'Generative artificial intelligence', 'summary': 'Generative artificial intelligence (Generative AI, GenAI, or GAI) is a subfield of artificial intelligence that uses generative models to produce text, images, videos, or other forms of data. These models learn the underlying patterns and structures of their training data and use them to produce new data based on the input, which often comes in the form of natural language prompts.\nGenerative AI tools have become more common since an "AI boom" in the 2020s. This boom was made possible by improvements in transformer-based deep neural networks, particularly large language models (LLMs). Major tools include chatbots such as ChatGPT, Copilot, Gemini, Grok, and DeepSeek; text-to-image models such as Stable Diffusion, Midjourney, and DALL-E; and text-to-video models such as Sora and Veo. Technology companies developing generative AI include OpenAI, Anthropic, Meta AI, Microsoft, Google, DeepSeek, and Baidu.\nGene

### Unstructured Loader

In [101]:
from langchain_unstructured import UnstructuredLoader

file_paths = [
    "data/syllabus.pdf",
    "data/speech.txt",
]


loader = UnstructuredLoader(file_paths)

In [102]:
docs = loader.load()

docs[0]

c:\Users\saina\.conda\envs\agentic_2_base\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
INFO: pikepdf C++ to Python logger bridge initialized


Document(metadata={'source': 'data/syllabus.pdf', 'coordinates': {'points': ((70.6844273048154, 572.8205481324769), (70.6844273048154, 603.315546861852), (150.75226966865517, 603.315546861852), (150.75226966865517, 572.8205481324769)), 'system': 'PixelSpace', 'layout_width': 612.0, 'layout_height': 791.9999937}, 'file_directory': 'data', 'filename': 'syllabus.pdf', 'languages': ['eng'], 'last_modified': '2025-01-31T12:12:36', 'page_number': 1, 'filetype': 'application/pdf', 'category': 'Title', 'element_id': '0c3f1e9f735af97d01ca9f4da78c7fdf'}, page_content='PYTHON + STATS')

## Text Splitter or Basic Chunking

### Text Splitting from Documents- RecursiveCharacter Text Splitters
This text splitter is the recommended one for generic text. It is parameterized by a list of characters. It tries to split on them in order until the chunks are small enough. The default list is ["\n\n", "\n", " ", ""]. This has the effect of trying to keep all paragraphs (and then sentences, and then words) together as long as possible, as those would generically seem to be the strongest semantically related pieces of text.

- How the text is split: by list of characters.
- How the chunk size is measured: by number of characters.

In [103]:
## Reading a PDf File
from langchain_community.document_loaders import PyPDFLoader
loader=PyPDFLoader('data\syllabus.pdf')
docs=loader.load()
docs

[Document(metadata={'producer': 'Canva', 'creator': 'Canva', 'creationdate': '2025-01-30T20:27:03+00:00', 'title': 'Ultimate Data Science & GenAI Bootcamp', 'moddate': '2025-01-30T20:26:59+00:00', 'keywords': 'DAGdmhcqnYw,BAEmsmap8Lg,0', 'author': 'monal singh', 'containsaigeneratedcontent': 'Yes', 'source': 'data\\syllabus.pdf', 'total_pages': 34, 'page': 0, 'page_label': '1'}, page_content='MACHINE\nLEARNING\nDEEP\nLEARNING\nPYTHON +\nSTATS\nCOMPUTER VISIONNATURAL LANGUAGE PROCESSING\nGENERATIVE AI\nRETRIEVAL AUGUMENT GENERATION\nVECTOR DB'),
 Document(metadata={'producer': 'Canva', 'creator': 'Canva', 'creationdate': '2025-01-30T20:27:03+00:00', 'title': 'Ultimate Data Science & GenAI Bootcamp', 'moddate': '2025-01-30T20:26:59+00:00', 'keywords': 'DAGdmhcqnYw,BAEmsmap8Lg,0', 'author': 'monal singh', 'containsaigeneratedcontent': 'Yes', 'source': 'data\\syllabus.pdf', 'total_pages': 34, 'page': 1, 'page_label': '2'}, page_content='This course is designed for aspiring data scientists,

In [104]:
len(docs)

34

34 Pages

In [105]:
from langchain_text_splitters import RecursiveCharacterTextSplitter
text_splitter=RecursiveCharacterTextSplitter(chunk_size=1000,chunk_overlap=100)
final_documents=text_splitter.split_documents(docs)
final_documents

[Document(metadata={'producer': 'Canva', 'creator': 'Canva', 'creationdate': '2025-01-30T20:27:03+00:00', 'title': 'Ultimate Data Science & GenAI Bootcamp', 'moddate': '2025-01-30T20:26:59+00:00', 'keywords': 'DAGdmhcqnYw,BAEmsmap8Lg,0', 'author': 'monal singh', 'containsaigeneratedcontent': 'Yes', 'source': 'data\\syllabus.pdf', 'total_pages': 34, 'page': 0, 'page_label': '1'}, page_content='MACHINE\nLEARNING\nDEEP\nLEARNING\nPYTHON +\nSTATS\nCOMPUTER VISIONNATURAL LANGUAGE PROCESSING\nGENERATIVE AI\nRETRIEVAL AUGUMENT GENERATION\nVECTOR DB'),
 Document(metadata={'producer': 'Canva', 'creator': 'Canva', 'creationdate': '2025-01-30T20:27:03+00:00', 'title': 'Ultimate Data Science & GenAI Bootcamp', 'moddate': '2025-01-30T20:26:59+00:00', 'keywords': 'DAGdmhcqnYw,BAEmsmap8Lg,0', 'author': 'monal singh', 'containsaigeneratedcontent': 'Yes', 'source': 'data\\syllabus.pdf', 'total_pages': 34, 'page': 1, 'page_label': '2'}, page_content='This course is designed for aspiring data scientists,

In [106]:
len(final_documents)

53

53 Chunks

In [107]:
final_documents[1]

Document(metadata={'producer': 'Canva', 'creator': 'Canva', 'creationdate': '2025-01-30T20:27:03+00:00', 'title': 'Ultimate Data Science & GenAI Bootcamp', 'moddate': '2025-01-30T20:26:59+00:00', 'keywords': 'DAGdmhcqnYw,BAEmsmap8Lg,0', 'author': 'monal singh', 'containsaigeneratedcontent': 'Yes', 'source': 'data\\syllabus.pdf', 'total_pages': 34, 'page': 1, 'page_label': '2'}, page_content='This course is designed for aspiring data scientists, machine learning enthusiasts, and\nprofessionals looking to build expertise in Python programming, data analysis, machine learning,\nand deep learning. Whether you are just starting or have some experience, this comprehensive\ncourse will equip you with the skills needed to work with real-world datasets, apply machine\nlearning algorithms, and deploy AI solutions. By the end of the course, you’ll have a solid\nfoundation in AI, a portfolio of end-to-end projects, and the confidence to tackle complex\nchallenges in data science and AI.\nLearning 

In [108]:
final_documents[1].page_content

'This course is designed for aspiring data scientists, machine learning enthusiasts, and\nprofessionals looking to build expertise in Python programming, data analysis, machine learning,\nand deep learning. Whether you are just starting or have some experience, this comprehensive\ncourse will equip you with the skills needed to work with real-world datasets, apply machine\nlearning algorithms, and deploy AI solutions. By the end of the course, you’ll have a solid\nfoundation in AI, a portfolio of end-to-end projects, and the confidence to tackle complex\nchallenges in data science and AI.\nLearning Objectives\nMaster Python Programming: Understand Python fundamentals, including data types,\ncontrol structures, and object-oriented programming, to write efficient and reusable\ncode.\nHandle Data with Pandas and NumPy: Acquire skills to manipulate, clean, and\npreprocess large datasets using Pandas and NumPy for data analysis tasks.'

In [109]:
final_documents[2].page_content

'preprocess large datasets using Pandas and NumPy for data analysis tasks.\nVisualize Data: Create compelling data visualizations using libraries such as Matplotlib,\nSeaborn, and Plotly to present insights effectively.\nUnderstand SQL & NoSQL: Gain expertise in both relational (SQL) and non-relational\n(NoSQL) databases, including MongoDB, for storing, querying, and managing data.\nGrasp Statistics and Probability: Understand the core concepts of statistics,\nprobability, and hypothesis testing, applying them to data analysis and machine\nlearning.\nMaster Machine Learning Techniques: Learn key machine learning algorithms,\nincluding supervised, unsupervised, and ensemble methods, and apply them to real-\nworld problems.\nDive into Deep Learning: Develop a strong understanding of neural networks, CNNs,\nRNNs, and transformers, with hands-on implementation for advanced AI tasks.\nExplore Generative AI & Vector Databases: Learn the concepts and applications of'

In [110]:
print(final_documents[0])
print()
print(final_documents[1])

page_content='MACHINE
LEARNING
DEEP
LEARNING
PYTHON +
STATS
COMPUTER VISIONNATURAL LANGUAGE PROCESSING
GENERATIVE AI
RETRIEVAL AUGUMENT GENERATION
VECTOR DB' metadata={'producer': 'Canva', 'creator': 'Canva', 'creationdate': '2025-01-30T20:27:03+00:00', 'title': 'Ultimate Data Science & GenAI Bootcamp', 'moddate': '2025-01-30T20:26:59+00:00', 'keywords': 'DAGdmhcqnYw,BAEmsmap8Lg,0', 'author': 'monal singh', 'containsaigeneratedcontent': 'Yes', 'source': 'data\\syllabus.pdf', 'total_pages': 34, 'page': 0, 'page_label': '1'}

page_content='This course is designed for aspiring data scientists, machine learning enthusiasts, and
professionals looking to build expertise in Python programming, data analysis, machine learning,
and deep learning. Whether you are just starting or have some experience, this comprehensive
course will equip you with the skills needed to work with real-world datasets, apply machine
learning algorithms, and deploy AI solutions. By the end of the course, you’ll have a

In [111]:
## Text Loader

from langchain_community.document_loaders import TextLoader

loader=TextLoader('data\speech.txt')
docs=loader.load()
docs

[Document(metadata={'source': 'data\\speech.txt'}, page_content='The world must be made safe for democracy. Its peace must be planted upon the tested foundations of political liberty. We have no selfish ends to serve. We desire no conquest, no dominion. We seek no indemnities for ourselves, no material compensation for the sacrifices we shall freely make. We are but one of the champions of the rights of mankind. We shall be satisfied when those rights have been made as secure as the faith and the freedom of nations can make them.\n\nJust because we fight without rancor and without selfish object, seeking nothing for ourselves but what we shall wish to share with all free peoples, we shall, I feel confident, conduct our operations as belligerents without passion and ourselves observe with proud punctilio the principles of right and of fair play we profess to be fighting for.\n\n…\n\nIt will be all the easier for us to conduct ourselves as belligerents in a high spirit of right and fairn

In [112]:
speech=""
with open("data\speech.txt") as f:
    speech=f.read()


text_splitter=RecursiveCharacterTextSplitter(chunk_size=100,chunk_overlap=20)
text=text_splitter.create_documents([speech])
print(text[0])
print(text[1])

page_content='The world must be made safe for democracy. Its peace must be planted upon the tested foundations of'
page_content='foundations of political liberty. We have no selfish ends to serve. We desire no conquest, no'


Great follow-up! Let's **deep dive into how `RecursiveCharacterTextSplitter` works** — especially the `chunk_size`, `chunk_overlap`, and how it handles different **separators**: `\n\n`, `\n`, `" "`, and `""`.

---

#### 🧠 Key Concepts

* **`chunk_size`**: Maximum number of characters in each chunk (not exact — best effort without breaking sentences/words).
* **`chunk_overlap`**: Number of characters to **repeat** from the previous chunk (for context).
* **`separators`**: Tries to split using bigger logical breaks first (`\n\n`, then `\n`, then `" "`, then `""`) to create cleaner chunks.

---

##### 🔤 Sample Text (includes all separators)

```python
text = """LangChain makes it easy to build LLM-powered apps.

It includes tools like text splitters, retrievers,
and agents. You can also integrate with OpenAI,
HuggingFace, and more!LangChain is open source.
"""
```

Note:

* `\n\n` → Between paragraphs
* `\n` → Between lines
* `" "` → Between words
* `""` → Between characters (last resort)

---

##### 🧪 Code with `RecursiveCharacterTextSplitter`

```python
from langchain.text_splitter import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=80,     # Try to keep each chunk under 80 chars
    chunk_overlap=20,  # Overlap 20 chars from the previous chunk
    separators=["\n\n", "\n", " ", ""]
)

chunks = text_splitter.split_text(text)
for i, chunk in enumerate(chunks):
    print(f"Chunk {i+1}:")
    print(repr(chunk))
    print('-' * 50)
```

---

##### 📦 Output Explanation:

```text
Chunk 1:
'LangChain makes it easy to build LLM-powered apps.'
--------------------------------------------------
Chunk 2:
'It includes tools like text splitters, retrievers,\nand agents. You can also'
--------------------------------------------------
Chunk 3:
'also integrate with OpenAI,\nHuggingFace, and more!LangChain is open source.'
--------------------------------------------------
```

---

##### 🔍 How it worked:

1. **Chunk 1**:

   * Stopped at `\n\n` (paragraph break), first level.
   * Length ≈ 50 chars, under `chunk_size`.

2. **Chunk 2**:

   * Uses `\n`, ` ` to split.
   * Includes **20-char overlap** from end of previous chunk (`"You can also..."`).

3. **Chunk 3**:

   * Uses ` ` and finally falls back to `""` if nothing else fits.
   * Ends with `"LangChain is open source."`

---

##### 📊 Visualization

| Step | Separator Used  | Text                          | Why                                |
| ---- | --------------- | ----------------------------- | ---------------------------------- |
| 1    | `\n\n`          | `"LangChain makes it..."`     | Clean paragraph                    |
| 2    | `\n`, `" "`     | `"It includes tools..."`      | Tries smaller break                |
| 3    | `" "` then `""` | `"You can also integrate..."` | Last part needs character fallback |

---

#### ✅ Final Notes

* **chunk\_size is soft**: It tries to keep chunks ≤ `chunk_size`, but prioritizes clean splits.
* **chunk\_overlap ensures continuity**: This is **critical** for keeping context in RAG systems.
* If no separator fits (e.g., a very long word), it **splits by characters** (`""`).

---

Would you like me to visualize this as a diagram or show a version that logs each step internally?


### How to split by character-Character Text Splitter
This is the simplest method. This splits based on a given character sequence, which defaults to "\n\n". Chunk length is measured by number of characters.

1. How the text is split: by single character separator.
2. How the chunk size is measured: by number of characters.


In [113]:
from langchain_text_splitters import CharacterTextSplitter
text_splitter=CharacterTextSplitter(separator="\n\n",chunk_size=100,chunk_overlap=20)
text_splitter.split_documents(docs)

[Document(metadata={'source': 'data\\speech.txt'}, page_content='The world must be made safe for democracy. Its peace must be planted upon the tested foundations of political liberty. We have no selfish ends to serve. We desire no conquest, no dominion. We seek no indemnities for ourselves, no material compensation for the sacrifices we shall freely make. We are but one of the champions of the rights of mankind. We shall be satisfied when those rights have been made as secure as the faith and the freedom of nations can make them.'),
 Document(metadata={'source': 'data\\speech.txt'}, page_content='Just because we fight without rancor and without selfish object, seeking nothing for ourselves but what we shall wish to share with all free peoples, we shall, I feel confident, conduct our operations as belligerents without passion and ourselves observe with proud punctilio the principles of right and of fair play we profess to be fighting for.'),
 Document(metadata={'source': 'data\\speech.t

In [114]:
speech=""
with open("data\speech.txt") as f:
    speech=f.read()


text_splitter=CharacterTextSplitter(chunk_size=100,chunk_overlap=20)
text=text_splitter.create_documents([speech])
print(text[0])
print(text[1])

page_content='The world must be made safe for democracy. Its peace must be planted upon the tested foundations of political liberty. We have no selfish ends to serve. We desire no conquest, no dominion. We seek no indemnities for ourselves, no material compensation for the sacrifices we shall freely make. We are but one of the champions of the rights of mankind. We shall be satisfied when those rights have been made as secure as the faith and the freedom of nations can make them.'
page_content='Just because we fight without rancor and without selfish object, seeking nothing for ourselves but what we shall wish to share with all free peoples, we shall, I feel confident, conduct our operations as belligerents without passion and ourselves observe with proud punctilio the principles of right and of fair play we profess to be fighting for.'


### How to split by HTML header
HTMLHeaderTextSplitter is a "structure-aware" chunker that splits text at the HTML element level and adds metadata for each header "relevant" to any given chunk. It can return chunks element by element or combine elements with the same metadata, with the objectives of (a) keeping related text grouped (more or less) semantically and (b) preserving context-rich information encoded in document structures. It can be used with other text splitters as part of a chunking pipeline.


In [115]:
from langchain_text_splitters import HTMLHeaderTextSplitter

html_string = """
<!DOCTYPE html>
<html>
<body>
    <div>
        <h1>Foo</h1>
        <p>Some intro text about Foo.</p>
        <div>
            <h2>Bar main section</h2>
            <p>Some intro text about Bar.</p>
            <h3>Bar subsection 1</h3>
            <p>Some text about the first subtopic of Bar.</p>
            <h3>Bar subsection 2</h3>
            <p>Some text about the second subtopic of Bar.</p>
        </div>
        <div>
            <h2>Baz</h2>
            <p>Some text about Baz</p>
        </div>
        <br>
        <p>Some concluding text about Foo</p>
    </div>
</body>
</html>
"""

headers_to_split_on=[
    ("h1","Header 1"),
    ("h2","Header 2"),
    ("h3","Header 3")
]

html_splitter=HTMLHeaderTextSplitter(headers_to_split_on)
html_header_splits=html_splitter.split_text(html_string)
html_header_splits

[Document(metadata={'Header 1': 'Foo'}, page_content='Foo'),
 Document(metadata={'Header 1': 'Foo'}, page_content='Some intro text about Foo.'),
 Document(metadata={'Header 1': 'Foo', 'Header 2': 'Bar main section'}, page_content='Bar main section'),
 Document(metadata={'Header 1': 'Foo', 'Header 2': 'Bar main section'}, page_content='Some intro text about Bar.'),
 Document(metadata={'Header 1': 'Foo', 'Header 2': 'Bar main section', 'Header 3': 'Bar subsection 1'}, page_content='Bar subsection 1'),
 Document(metadata={'Header 1': 'Foo', 'Header 2': 'Bar main section', 'Header 3': 'Bar subsection 1'}, page_content='Some text about the first subtopic of Bar.'),
 Document(metadata={'Header 1': 'Foo', 'Header 2': 'Bar main section', 'Header 3': 'Bar subsection 2'}, page_content='Bar subsection 2'),
 Document(metadata={'Header 1': 'Foo', 'Header 2': 'Bar main section', 'Header 3': 'Bar subsection 2'}, page_content='Some text about the second subtopic of Bar.'),
 Document(metadata={'Header 

### How to split JSON data
This json splitter splits json data while allowing control over chunk sizes. It traverses json data depth first and builds smaller json chunks. It attempts to keep nested json objects whole but will split them if needed to keep chunks between a min_chunk_size and the max_chunk_size.

If the value is not a nested json, but rather a very large string the string will not be split. If you need a hard cap on the chunk size consider composing this with a Recursive Text splitter on those chunks. There is an optional pre-processing step to split lists, by first converting them to json (dict) and then splitting them as such.

- How the text is split: json value.
- How the chunk size is measured: by number of characters.

In [116]:
import json
import requests

json_data=requests.get("https://api.smith.langchain.com/openapi.json").json()

In [117]:
json_data

{'openapi': '3.1.0',
 'info': {'title': 'LangSmith', 'version': '0.1.0'},
 'paths': {'/api/v1/sessions/{session_id}/dashboard': {'post': {'tags': ['tracer-sessions'],
    'summary': 'Get Tracing Project Prebuilt Dashboard',
    'description': 'Get a prebuilt dashboard for a tracing project.',
    'operationId': 'get_tracing_project_prebuilt_dashboard_api_v1_sessions__session_id__dashboard_post',
    'security': [{'API Key': []}, {'Tenant ID': []}, {'Bearer Auth': []}],
    'parameters': [{'name': 'session_id',
      'in': 'path',
      'required': True,
      'schema': {'type': 'string', 'format': 'uuid', 'title': 'Session Id'}},
     {'name': 'accept',
      'in': 'header',
      'required': False,
      'schema': {'anyOf': [{'type': 'string'}, {'type': 'null'}],
       'title': 'Accept'}}],
    'requestBody': {'required': True,
     'content': {'application/json': {'schema': {'$ref': '#/components/schemas/CustomChartsSectionRequest'}}}},
    'responses': {'200': {'description': 'Succ

In [118]:
from langchain_text_splitters import RecursiveJsonSplitter
json_splitter=RecursiveJsonSplitter(max_chunk_size=300)
json_chunks=json_splitter.split_json(json_data)
json_chunks

[{'openapi': '3.1.0',
  'info': {'title': 'LangSmith', 'version': '0.1.0'},
  'paths': {'/api/v1/sessions/{session_id}/dashboard': {'post': {'tags': ['tracer-sessions'],
     'summary': 'Get Tracing Project Prebuilt Dashboard',
     'description': 'Get a prebuilt dashboard for a tracing project.'}}}},
 {'paths': {'/api/v1/sessions/{session_id}/dashboard': {'post': {'operationId': 'get_tracing_project_prebuilt_dashboard_api_v1_sessions__session_id__dashboard_post',
     'security': [{'API Key': []}, {'Tenant ID': []}, {'Bearer Auth': []}]}}}},
 {'paths': {'/api/v1/sessions/{session_id}/dashboard': {'post': {'parameters': [{'name': 'session_id',
       'in': 'path',
       'required': True,
       'schema': {'type': 'string', 'format': 'uuid', 'title': 'Session Id'}},
      {'name': 'accept',
       'in': 'header',
       'required': False,
       'schema': {'anyOf': [{'type': 'string'}, {'type': 'null'}],
        'title': 'Accept'}}]}}}},
 {'paths': {'/api/v1/sessions/{session_id}/dashb

In [119]:
json_chunks[0]

{'openapi': '3.1.0',
 'info': {'title': 'LangSmith', 'version': '0.1.0'},
 'paths': {'/api/v1/sessions/{session_id}/dashboard': {'post': {'tags': ['tracer-sessions'],
    'summary': 'Get Tracing Project Prebuilt Dashboard',
    'description': 'Get a prebuilt dashboard for a tracing project.'}}}}

In [120]:
json_chunks[1]

{'paths': {'/api/v1/sessions/{session_id}/dashboard': {'post': {'operationId': 'get_tracing_project_prebuilt_dashboard_api_v1_sessions__session_id__dashboard_post',
    'security': [{'API Key': []}, {'Tenant ID': []}, {'Bearer Auth': []}]}}}}

A **recursive JSON splitter** is a method used to **break down large or deeply nested JSON data** into smaller, more manageable chunks—typically for processing with language models like GPT.

This technique is especially useful when dealing with:

* Large JSON documents
* Nested dictionaries and lists
* APIs that return complex data
* Streaming or chunked ingestion into LLM pipelines

---

#### 🔍 Why "Recursive"?

Because the splitter **recursively traverses** the structure of the JSON—exploring dictionaries and lists inside dictionaries and lists—until it finds atomic elements (like strings, numbers), and breaks them into chunks without losing the hierarchy.

---

#### 🧠 Use Case in LLMs / LangChain

LangChain and other frameworks use recursive splitting to:

* **Preserve context** in nested JSON
* Avoid hallucination by keeping chunk boundaries aligned with logical JSON blocks
* Enable **semantic chunking** for RAG or summarization

---

#### ✅ Example

Suppose you have the following JSON:

```json
{
  "patient": {
    "name": "John",
    "age": 30,
    "medical_history": [
      {
        "condition": "Diabetes",
        "medications": ["Metformin", "Insulin"]
      },
      {
        "condition": "Hypertension",
        "medications": ["Amlodipine"]
      }
    ]
  }
}
```

A **recursive JSON splitter** would:

* Traverse into `"patient"` → `"medical_history"` → individual entries
* Split **each condition block** into a separate chunk:

  * Chunk 1: `{"condition": "Diabetes", "medications": ["Metformin", "Insulin"]}`
  * Chunk 2: `{"condition": "Hypertension", "medications": ["Amlodipine"]}`

This is **better than naive string chunking**, because it preserves meaning and structure.

---

#### 🔧 In LangChain

If you're using LangChain's `RecursiveJsonSplitter`, it works like this:

```python
from langchain.text_splitter import RecursiveJsonSplitter

splitter = RecursiveJsonSplitter(max_chunk_size=500, chunk_overlap=0)
chunks = splitter.split_json(json_data)
```

* `max_chunk_size`: Defines the size limit per chunk (based on character count or tokens)
* `chunk_overlap`: Optional overlap between chunks to preserve context
* Works recursively to maintain JSON integrity

---

#### 📌 Summary

| Feature   | Description                                                               |
| --------- | ------------------------------------------------------------------------- |
| Purpose   | Break down large/nested JSON into manageable chunks                       |
| Recursive | Traverses dictionaries and lists recursively                              |
| Benefits  | Preserves structure, avoids hallucination, better for LLMs                |
| Used in   | LLM preprocessing, LangChain, RAG pipelines, indexing large API responses |

Would you like a working Python example?


## Vector Embeddings

In [1]:
import os
from dotenv import load_dotenv
load_dotenv() 

True

### Open AI Embeddings

In [2]:
from langchain_openai import OpenAIEmbeddings

embeddings = OpenAIEmbeddings(model="text-embedding-3-large")

In [3]:
embeddings

OpenAIEmbeddings(client=<openai.resources.embeddings.Embeddings object at 0x000002A9FE4BBFD0>, async_client=<openai.resources.embeddings.AsyncEmbeddings object at 0x000002A9FE4D9750>, model='text-embedding-3-large', dimensions=None, deployment='text-embedding-ada-002', openai_api_version=None, openai_api_base=None, openai_api_type=None, openai_proxy=None, embedding_ctx_length=8191, openai_api_key=SecretStr('**********'), openai_organization=None, allowed_special=None, disallowed_special=None, chunk_size=1000, max_retries=2, request_timeout=None, headers=None, tiktoken_enabled=True, tiktoken_model_name=None, show_progress_bar=False, model_kwargs={}, skip_empty=False, default_headers=None, default_query=None, retry_min_seconds=4, retry_max_seconds=20, http_client=None, http_async_client=None, check_embedding_ctx_length=True)

In [ ]:
text="This is a tutorial on OPENAI embeddings"
query_result=embeddings.embed_query(text)

In [5]:
print(query_result)

[-0.004172635264694691, 0.04088858142495155, -0.018989549949765205, -0.040317077189683914, 0.022639388218522072, 0.0011016082717105746, 0.012306839227676392, 0.052162814885377884, -0.01040398795157671, 0.004925983026623726, -0.017158137634396553, 0.00635799253359437, -0.01021565031260252, -0.011689873412251472, 0.01118331216275692, 0.018197236582636833, 0.022327659651637077, 0.04930528998374939, -0.018041372299194336, -0.02043130062520504, 0.0024224016815423965, 0.006910014431923628, -0.049798861145973206, -0.03958970680832863, 0.026302216574549675, -0.0198078416287899, 0.010533874854445457, 0.039044179022312164, -0.00887131504714489, 0.05185108259320259, 0.012683512642979622, -0.011345671489834785, 0.002898114500567317, -0.002060340251773596, -0.015365689992904663, 0.019002540037035942, 0.042810916900634766, 0.03299142047762871, -0.040369030088186264, 0.02387331984937191, 0.029380548745393753, 0.003831680864095688, 0.0022373120300471783, -0.021587301045656204, -0.051175668835639954, -

In [7]:
len(query_result)

3072

* 3072 Open AI Default Embedding Dimension 

In [8]:
from langchain_openai import OpenAIEmbeddings

embeddings = OpenAIEmbeddings(model="text-embedding-3-large",dimensions=1024)

In [9]:
text="This is a tutorial on OPENAI embedding"
query_result=embeddings.embed_query(text)
len(query_result)

1024

### Converting the text file to Embedding

In [10]:
from langchain_community.document_loaders import TextLoader

loader=TextLoader('data\speech.txt')
docs=loader.load()
docs

[Document(metadata={'source': 'data\\speech.txt'}, page_content='The world must be made safe for democracy. Its peace must be planted upon the tested foundations of political liberty. We have no selfish ends to serve. We desire no conquest, no dominion. We seek no indemnities for ourselves, no material compensation for the sacrifices we shall freely make. We are but one of the champions of the rights of mankind. We shall be satisfied when those rights have been made as secure as the faith and the freedom of nations can make them.\n\nJust because we fight without rancor and without selfish object, seeking nothing for ourselves but what we shall wish to share with all free peoples, we shall, I feel confident, conduct our operations as belligerents without passion and ourselves observe with proud punctilio the principles of right and of fair play we profess to be fighting for.\n\n…\n\nIt will be all the easier for us to conduct ourselves as belligerents in a high spirit of right and fairn

In [11]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter=RecursiveCharacterTextSplitter(chunk_size=500,chunk_overlap=50)
final_documents=text_splitter.split_documents(docs)
final_documents

[Document(metadata={'source': 'data\\speech.txt'}, page_content='The world must be made safe for democracy. Its peace must be planted upon the tested foundations of political liberty. We have no selfish ends to serve. We desire no conquest, no dominion. We seek no indemnities for ourselves, no material compensation for the sacrifices we shall freely make. We are but one of the champions of the rights of mankind. We shall be satisfied when those rights have been made as secure as the faith and the freedom of nations can make them.'),
 Document(metadata={'source': 'data\\speech.txt'}, page_content='Just because we fight without rancor and without selfish object, seeking nothing for ourselves but what we shall wish to share with all free peoples, we shall, I feel confident, conduct our operations as belligerents without passion and ourselves observe with proud punctilio the principles of right and of fair play we profess to be fighting for.\n\n…'),
 Document(metadata={'source': 'data\\spe

In [12]:
print(embeddings.embed_query(final_documents[0].page_content))

[0.02978353761136532, -0.02298765629529953, -0.006728641223162413, 0.07846644520759583, 0.014416594989597797, 0.011153137311339378, -0.024529729038476944, 0.021660754457116127, 0.03467872366309166, 0.03209664672613144, 0.01949109323322773, 0.13821282982826233, -0.03252699598670006, -0.018226951360702515, -0.005980018060654402, -0.020477302372455597, -0.034266311675310135, 0.01673867180943489, -0.059351902455091476, 0.0013381075114011765, -0.02476283349096775, -0.0066838134080171585, -0.03301113471388817, -0.0018390573095530272, 0.03224009647965431, 0.029693882912397385, -0.008454508148133755, 0.011045550927519798, 0.040667708963155746, 0.07240573316812515, -0.000987890874966979, 0.01852281391620636, 0.03616700693964958, -0.002884663874283433, 0.08047472685575485, 0.01122486125677824, 0.008261749520897865, 0.01825384795665741, -0.01813729666173458, 0.06548433750867844, -0.008140713907778263, -0.024422142654657364, 0.040560122579336166, 0.0011117274407297373, 0.06265122443437576, 0.04299

### Hugging face embeddings

#### Sentence Transformers on Hugging Face
Hugging Face sentence-transformers is a Python framework for state-of-the-art sentence, text and image embeddings. One of the embedding models is used in the HuggingFaceEmbeddings class. We have also added an alias for SentenceTransformerEmbeddings for users who are more familiar with directly using that package.

In [17]:
from langchain_huggingface import HuggingFaceEmbeddings
embeddings=HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

c:\Users\saina\.conda\envs\agentic_2_base\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\saina\.conda\envs\agentic_2_base\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\saina\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrat

In [18]:
embeddings

HuggingFaceEmbeddings(model_name='all-MiniLM-L6-v2', cache_folder=None, model_kwargs={}, encode_kwargs={}, query_encode_kwargs={}, multi_process=False, show_progress=False)

In [19]:
text="this is latest documents"
query_result=embeddings.embed_query(text)


In [20]:
print(query_result)

[-0.022454164922237396, 0.038852039724588394, 0.01915658265352249, -0.03187502548098564, 0.06090155616402626, -0.011868435889482498, -0.058810755610466, 0.021520663052797318, -0.01433353777974844, 0.06845016777515411, 0.0298055037856102, 0.08322732150554657, -0.05888832360506058, 0.044100768864154816, -0.051475632935762405, 0.046506088227033615, 0.009405876509845257, -0.06307179480791092, -0.034133218228816986, 0.038223255425691605, -0.07167800515890121, 0.052359096705913544, 0.0014817501651123166, -0.04784122109413147, 0.03052069991827011, 0.0370621383190155, -0.09956248849630356, -0.09303517639636993, 0.03765542060136795, -0.05265168100595474, -0.03268291801214218, 0.05249091237783432, 0.04450400546193123, -0.0008237860165536404, 0.04728083312511444, -0.018870588392019272, 0.06194909289479256, -0.022268639877438545, 0.035890933126211166, 0.02039726823568344, -0.03495148941874504, -0.12224896252155304, -0.047862228006124496, 0.0331137478351593, 0.014004863798618317, 0.0628273263573646

In [21]:
len(query_result)

384

* Length of Hugging face 'all-MiniLM-L6-v2' is 384

### Similarity Scores

In [22]:
from langchain_huggingface import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-mpnet-base-v2")

c:\Users\saina\.conda\envs\agentic_2_base\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\saina\.cache\huggingface\hub\models--sentence-transformers--all-mpnet-base-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Fallin

In [23]:
vectors=embeddings.embed_query("Hello, world!")
len(vectors)

768

#### Cosine similarity

In [25]:
from sklearn.metrics.pairwise import cosine_similarity

In [26]:
documents=["what is a capital of USA?",
           "Who is a president of USA?",
           "Who is a prime minister of India?"]

In [27]:
my_query="Narendra modi is prime minister of india?"

In [28]:
document_embedding=embeddings.embed_documents(documents)

In [33]:
print(document_embedding)

[[-0.00881790742278099, 0.00996183231472969, -0.0037635762710124254, 0.014642719179391861, 0.017020726576447487, 0.029038697481155396, -0.03265979513525963, -0.0048144967295229435, 0.022072231397032738, 0.003794062649831176, 0.04156198725104332, -0.03174193575978279, 0.08012624084949493, -0.012714259326457977, 0.02981201931834221, -0.03687666356563568, 0.011505870148539543, -0.022644827142357826, 0.004705741070210934, 0.015170547179877758, -0.017198733985424042, 0.014418408274650574, -0.01744326762855053, -0.017365803942084312, -0.007212973665446043, 0.049505025148391724, -0.020312966778874397, -0.012819604948163033, -0.02388736791908741, 0.021178731694817543, 0.09666013717651367, -0.011242177337408066, -0.01813976839184761, -0.07269251346588135, 1.4123102118901443e-06, -0.03320291265845299, 0.0070005073212087154, 0.003453637473285198, 0.021958794444799423, -0.027472928166389465, -0.012029504403471947, 0.017864106222987175, 0.0022845780476927757, 0.04842032119631767, -0.022159865126013

In [36]:
len(document_embedding)

3

In [37]:
query_embedding=embeddings.embed_query(my_query)

In [38]:
len(query_embedding)

768

In [39]:
cosine_similarity([query_embedding],document_embedding)

array([[0.17969954, 0.35317218, 0.68155701]])

#### Euclidean distances

In [40]:
from sklearn.metrics.pairwise import euclidean_distances

In [41]:
euclidean_distances([query_embedding], document_embedding)

array([[1.28085945, 1.13738982, 0.79805135]])

| Metric            | Similarity Score Range | Behavior                              |
| ----------------- | ---------------------- | ------------------------------------- |
| Cosine Similarity | \[-1, 1]               | Focuses on angle only |
| L2 Distance       | \[0, ∞)                | Focuses on **magnitude + direction**  |


### Vector Store

#### FAISS

In [43]:
import faiss
from langchain_community.vectorstores import FAISS
from langchain_community.docstore.in_memory import InMemoryDocstore

In [45]:
index=faiss.IndexFlatL2(768)

In [46]:
index

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x000002A9C20EAF10> >

In [47]:
vector_store=FAISS(
    embedding_function=embeddings,
    index=index,
    docstore=InMemoryDocstore(),
    index_to_docstore_id={},
)


In [48]:
vector_store.add_texts(["AI is future","AI is powerful","Dogs are cute"])

['6bbd4245-6eaf-478f-8428-5e2d71c012c8', '6d5e7133-2722-4ef5-aee7-ccf45dc19fcf', '3f8c20cb-d710-4be7-81db-e3dae7749cd6']

In [49]:
vector_store.index_to_docstore_id

{0: '6bbd4245-6eaf-478f-8428-5e2d71c012c8', 1: '6d5e7133-2722-4ef5-aee7-ccf45dc19fcf', 2: '3f8c20cb-d710-4be7-81db-e3dae7749cd6'}

In [50]:
results = vector_store.similarity_search("Tell me about AI", k=3)

In [51]:
results


[Document(id='6bbd4245-6eaf-478f-8428-5e2d71c012c8', metadata={}, page_content='AI is future'), Document(id='6d5e7133-2722-4ef5-aee7-ccf45dc19fcf', metadata={}, page_content='AI is powerful'), Document(id='3f8c20cb-d710-4be7-81db-e3dae7749cd6', metadata={}, page_content='Dogs are cute')]

| Feature               | `Flat`                | `IVF` (Inverted File Index)        | `HNSW` (Graph-based Index)          |
| --------------------- | --------------------- | ---------------------------------- | ----------------------------------- |
| Type of Search     | Exact                 | Approximate (cluster-based)        | Approximate (graph-based traversal) |
| Speed               | Slow (linear scan)    | Fast (search only in top clusters) | Very Fast (graph walk)              |


| Dataset Size              | Recommended Index                 |
| ------------------------- | --------------------------------- |
| UPTO 1L                     | `IndexFlatL2` or `IndexFlatIP`    |
| UPTO 1M                  | `IndexIVFFlat` or `IndexHNSWFlat` |
| > 1M                      | `IndexIVFPQ` or `IndexHNSWFlat`   |


#### Documents with metadata

In [52]:
# from uuid import uuid4
from langchain_core.documents import Document

document_1 = Document(
    page_content="I had chocolate chip pancakes and scrambled eggs for breakfast this morning.",
    metadata={"source": "tweet"},
)

document_2 = Document(
    page_content="The weather forecast for tomorrow is cloudy and overcast, with a high of 62 degrees.",
    metadata={"source": "news"},
)

document_3 = Document(
    page_content="Building an exciting new project with LangChain - come check it out!",
    metadata={"source": "tweet"},
)

document_4 = Document(
    page_content="Robbers broke into the city bank and stole $1 million in cash.",
    metadata={"source": "news"},
)

document_5 = Document(
    page_content="Wow! That was an amazing movie. I can't wait to see it again.",
    metadata={"source": "tweet"},
)

document_6 = Document(
    page_content="Is the new iPhone worth the price? Read this review to find out.",
    metadata={"source": "website"},
)

document_7 = Document(
    page_content="The top 10 soccer players in the world right now.",
    metadata={"source": "website"},
)

document_8 = Document(
    page_content="LangGraph is the best framework for building stateful, agentic applications!",
    metadata={"source": "tweet"},
)

document_9 = Document(
    page_content="The stock market is down 500 points today due to fears of a recession.",
    metadata={"source": "news"},
)

document_10 = Document(
    page_content="I have a bad feeling I am going to get deleted :(",
    metadata={"source": "tweet"},
)

documents = [
    document_1,
    document_2,
    document_3,
    document_4,
    document_5,
    document_6,
    document_7,
    document_8,
    document_9,
    document_10,
]

In [54]:
index=faiss.IndexFlatIP(768)
vector_store=FAISS(
    embedding_function=embeddings,
    index=index,
    docstore=InMemoryDocstore(),
    index_to_docstore_id={},
)

In [55]:
vector_store.add_documents(documents=documents)

['08974828-dfbb-4266-a215-c6a1a78e7efe', 'c3d8c411-d6eb-4a18-8a27-9f44b587b6b8', 'cdab9ee1-6947-430e-8c89-ca6c4feb0717', '50515a67-eee1-4728-aeb1-de0639a0ab12', 'a5b7dc9e-c344-43d9-a5d7-6cbfffd5fbc3', 'fc931efa-4034-4c29-9934-3bb0e62799d0', 'ff641fd7-4297-4b1c-821b-cc267654ef3e', 'd076af9a-38d6-4978-bde5-5ce099441379', '4dbedf50-1bca-49f3-9423-2fd07a6ab695', '419fd0f8-ab7b-40fe-ad43-2a73007aaee1']

In [56]:
vector_store.similarity_search(
    "LangChain provides abstractions to make working with LLMs easy",
    k=2 #hyperparameter
    
)

[Document(id='cdab9ee1-6947-430e-8c89-ca6c4feb0717', metadata={'source': 'tweet'}, page_content='Building an exciting new project with LangChain - come check it out!'), Document(id='d076af9a-38d6-4978-bde5-5ce099441379', metadata={'source': 'tweet'}, page_content='LangGraph is the best framework for building stateful, agentic applications!')]

In [57]:
vector_store.similarity_search(
    "LangChain provides abstractions to make working with LLMs easy",
    #k=2 #hyperparameter,
    filter={"source":{"$eq": "tweet"}}
    
)

[Document(id='cdab9ee1-6947-430e-8c89-ca6c4feb0717', metadata={'source': 'tweet'}, page_content='Building an exciting new project with LangChain - come check it out!'), Document(id='d076af9a-38d6-4978-bde5-5ce099441379', metadata={'source': 'tweet'}, page_content='LangGraph is the best framework for building stateful, agentic applications!'), Document(id='a5b7dc9e-c344-43d9-a5d7-6cbfffd5fbc3', metadata={'source': 'tweet'}, page_content="Wow! That was an amazing movie. I can't wait to see it again."), Document(id='08974828-dfbb-4266-a215-c6a1a78e7efe', metadata={'source': 'tweet'}, page_content='I had chocolate chip pancakes and scrambled eggs for breakfast this morning.')]

In [58]:
result=vector_store.similarity_search(
    "LangChain provides abstractions to make working with LLMs easy",
    #k=2 #hyperparameter,
    filter={"source":"news"}
    
)

In [59]:
result[0].metadata

{'source': 'news'}

In [60]:
result[0].page_content

'Robbers broke into the city bank and stole $1 million in cash.'

In [61]:
retriever=vector_store.as_retriever(search_kwargs={"k": 3})

In [62]:
retriever.invoke("LangChain provides abstractions to make working with LLMs easy")

[Document(id='cdab9ee1-6947-430e-8c89-ca6c4feb0717', metadata={'source': 'tweet'}, page_content='Building an exciting new project with LangChain - come check it out!'), Document(id='d076af9a-38d6-4978-bde5-5ce099441379', metadata={'source': 'tweet'}, page_content='LangGraph is the best framework for building stateful, agentic applications!'), Document(id='fc931efa-4034-4c29-9934-3bb0e62799d0', metadata={'source': 'website'}, page_content='Is the new iPhone worth the price? Read this review to find out.')]

In [63]:
vector_store.save_local("today's class faiss index")

In [64]:
new_vector_store=FAISS.load_local(
  "today's class faiss index",embeddings ,allow_dangerous_deserialization=True
)

In [65]:
new_vector_store.similarity_search("langchain")

[Document(id='cdab9ee1-6947-430e-8c89-ca6c4feb0717', metadata={'source': 'tweet'}, page_content='Building an exciting new project with LangChain - come check it out!'), Document(id='d076af9a-38d6-4978-bde5-5ce099441379', metadata={'source': 'tweet'}, page_content='LangGraph is the best framework for building stateful, agentic applications!'), Document(id='08974828-dfbb-4266-a215-c6a1a78e7efe', metadata={'source': 'tweet'}, page_content='I had chocolate chip pancakes and scrambled eggs for breakfast this morning.'), Document(id='ff641fd7-4297-4b1c-821b-cc267654ef3e', metadata={'source': 'website'}, page_content='The top 10 soccer players in the world right now.')]

In [ ]:
from langchain_community.document_loaders import PyPDFLoader

In [68]:
FILE_PATH = r"C:\Users\saina\Desktop\DS_ML_AI\Krish_Naik_Courses\Krish_naik_1_Agentic_AI_and_Gen_AI\Practice\agentic_ai_2\data\llama2.pdf"

In [70]:
from langchain_community.document_loaders import PyPDFLoader
loader = PyPDFLoader(FILE_PATH)

In [71]:
len(loader.load())

77

* 77 Pages PDF
* 13.4 seconds to loads

In [72]:
pages = []
async for page in loader.alazy_load():
    pages.append(page)

* Async lazy load is faster here

In [73]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

In [74]:
splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,#hyperparameter
    chunk_overlap=50 #hyperparemeter
)

In [75]:
split_docs = splitter.split_documents(pages)

In [76]:
len(split_docs)

615

In [80]:
index=faiss.IndexFlatIP(768)
vector_store=FAISS(
    embedding_function=embeddings,
    index=index,
    docstore=InMemoryDocstore(),
    index_to_docstore_id={},
)

In [81]:
vector_store.add_documents(documents=split_docs)

['cb782097-4c91-42d7-a720-89e2e137f918', 'a97a36ac-ce47-4111-9ab3-ec28db57cbc2', 'f170b72b-fed1-4396-b62f-08eaf1935a67', '7798f636-f21e-49a9-a757-f3c129e1e873', '89576f26-4732-4f5f-8d14-8e817b85a0c5', 'ec27c377-da77-4c02-895e-4f18b002236e', 'a218ce1b-74a1-433e-8ae1-bd1cf6ab3503', 'dd18ca04-92b4-4c7a-8d1a-b3f3ef40cc0c', 'df1a08b8-26b5-45f8-a5bc-c0ecafed4d31', '4b3b220a-1199-4e45-b4db-33bd01efb28c', '746ffe52-c1c6-4d09-8514-0ea83f1fda7f', '388072c4-f554-4371-b45b-ab07f13c7a40', '303e374e-7a6d-4158-861c-e34b6583dd6e', '6f197bdd-f1ce-4415-8264-7b4c9ec86642', '5bc336cc-189e-4c5e-b7af-9c717976a32c', '5d303eb6-c11f-41d6-a878-1084eefbab45', 'c0fbbb3a-12cd-4634-acc1-1a4bb0cd11fc', '2b4aa059-8e81-4f6e-a943-c3c831073edf', 'f8a9ac07-0010-41ef-9d3a-21619a5e4f9a', '36210616-f51a-416e-af57-bf656bf166b8', '9c6041aa-82db-49ab-b7a1-a50801653b0d', 'e7fde322-a6ab-41bd-a4c2-ce0206c128e4', '0e3f713e-c181-4e71-aaf1-d845a09b24be', 'e1ff1d6c-a650-4374-aa7a-d4a804fa6a18', '4996033c-14ee-4a40-927a-6717e371e1d0',

In [82]:
retriever=vector_store.as_retriever(
    search_kwargs={"k": 10} #hyperparameter
)

In [83]:
retriever.invoke("what is llama model?")

[Document(id='5efb9ab5-7962-4e55-8211-fbb56ad0655e', metadata={'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '', 'moddate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'subject': '', 'title': '', 'trapped': '/False', 'source': 'C:\\Users\\saina\\Desktop\\DS_ML_AI\\Krish_Naik_Courses\\Krish_naik_1_Agentic_AI_and_Gen_AI\\Practice\\agentic_ai_2\\data\\llama2.pdf', 'total_pages': 77, 'page': 76, 'page_label': '77'}, page_content='specific applications of the model. Please see the Responsible Use Guide available available at\nhttps://ai.meta.com/llama/responsible-user-guide\nTable 52: Model card forLlama 2.\n77'), Document(id='4996033c-14ee-4a40-927a-6717e371e1d0', metadata={'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '',

In [84]:
from langchain_google_genai import ChatGoogleGenerativeAI
model=ChatGoogleGenerativeAI(model='gemini-1.5-flash')

In [85]:
from langchain import hub
prompt = hub.pull("rlm/rag-prompt")

In [86]:
import pprint
pprint.pprint(prompt.messages)

[HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['context', 'question'], input_types={}, partial_variables={}, template="You are an assistant for question-answering tasks. Use the following pieces of retrieved context to answer the question. If you don't know the answer, just say that you don't know. Use three sentences maximum and keep the answer concise.\nQuestion: {question} \nContext: {context} \nAnswer:"), additional_kwargs={})]


In [87]:
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough

In [88]:
# context(retriever),prompt(hub),model(google),parser(langchain)
def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)
    

In [89]:
rag_chain = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | prompt
    | model
    | StrOutputParser()
)

In [90]:
rag_chain.invoke("what is llama model?")

'Llama is a large language model developed by Meta.  It comes in various sizes, from 7B to 65B parameters, and has both pretrained and fine-tuned versions (Llama 2).  The model is intended for commercial and research use, primarily in English.'

### Key Points
- Research suggests exploring embeddings, vector stores, and similarity search techniques can enhance AI applications like RAG systems.
- It seems likely that using tools like Hugging Face, FAISS, and Pinecone can help in practical implementation.
- The evidence leans toward experimenting with different embedding models and vector stores for better performance.

#### Getting Started with Embeddings
Embeddings turn text into numbers for AI to understand. Start with free options like Hugging Face's "all-MiniLM-L6-v2" or paid ones like OpenAI for accuracy. Try them out using Python libraries like LangChain to see which fits your needs.

#### Diving into Vector Stores
Vector stores are like special databases for these numbers. Use FAISS for local, fast storage or cloud options like Pinecone for scalability. Each has pros, so test them with your data to see what works best.

#### Exploring Similarity Search
This is how AI finds similar items, like matching questions to answers. Try cosine similarity for text and L2 distance for other data. Experiment with exact and approximate search methods to balance speed and accuracy.

---

### Survey Note: Exploring Embeddings, Vector Stores, and Similarity Search Techniques

This note provides a comprehensive guide to exploring embeddings, vector stores, and similarity search techniques, building on the foundational concepts from a recent lecture on vector databases and Retrieval-Augmented Generation (RAG) systems. The discussion is informed by the lecture content, which covered embeddings, vector databases, and similarity search, and extends to practical steps, tools, and resources for deeper exploration. The current time is 03:02 PM IST on Wednesday, June 18, 2025, and this note aims to provide a detailed, professional overview for practitioners and learners in AI and machine learning.

#### Introduction to Embeddings

Embeddings are numerical representations of text or other data, capturing semantic relationships in a high-dimensional space. They are crucial for tasks like similarity search, clustering, and retrieval in RAG systems. The lecture highlighted various embedding types, and further exploration can enhance understanding and application.

##### Types of Embeddings
- **OpenAI Embeddings**: These are highly accurate, suitable for tasks requiring precision, but require an API key and can be costly for large-scale use. For example, the model "text-embedding-3-large" generates 3072-dimensional vectors. Usage involves the OpenAI API, as shown:
  ```python
  import openai
  openai.api_key = "your_api_key"
  response = openai.Embedding.create(input="Your text here", model="text-embedding-3-large")
  embedding = response["data"][0]["embedding"]
  ```
  - **Resource**: [OpenAI Embeddings Documentation](https://platform.openai.com/docs/guides/embeddings)

- **Hugging Face Embeddings**: Open-source and free, these are popular for their balance of speed and accuracy. Models like "all-MiniLM-L6-v2" generate 384-dimensional vectors, suitable for local deployment. Example implementation:
  ```python
  from transformers import AutoModel, AutoTokenizer
  model_name = "sentence-transformers/all-MiniLM-L6-v2"
  tokenizer = AutoTokenizer.from_pretrained(model_name)
  model = AutoModel.from_pretrained(model_name)
  text = "Hello, AI"
  inputs = tokenizer(text, return_tensors="pt")
  outputs = model(**inputs)
  embedding = outputs.last_hidden_state.mean(dim=1).squeeze().tolist()
  ```
  - **Resource**: [Hugging Face Embeddings](https://huggingface.co/models?filter=sentence-transformers)

- **Other Options**: Google Gemini, Azure OpenAI, AWS Bedrock, and Ollama offer embeddings with varying trade-offs in cost, speed, and accuracy. For instance, Google Gemini provides embeddings through their API, while Ollama supports local LLM servers for embedding generation.

##### Comparing Embeddings
To explore further, compare embeddings based on:
- **Dimensionality**: Higher dimensions (e.g., 3072 for OpenAI) capture more information but may slow down computations.
- **Semantic Quality**: Test how well they capture relationships, such as "King - Man + Woman = Queen," using evaluation metrics like cosine similarity.
- **Speed**: Hugging Face models are generally faster for local use, while API-based models may have latency.
- **Cost**: Open-source models are free, while API-based ones incur costs, making cost-benefit analysis essential.

##### Tools for Exploration
- **LangChain**: Simplifies working with embeddings across providers. Example:
  ```python
  from langchain.embeddings import OpenAIEmbeddings, HuggingFaceEmbeddings
  openai_embeddings = OpenAIEmbeddings()
  hf_embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
  ```
- **Sentence Transformers**: A library for creating sentence embeddings, ideal for research and prototyping:
  ```python
  from sentence_transformers import SentenceTransformer
  model = SentenceTransformer("all-MiniLM-L6-v2")
  embeddings = model.encode(["Hello", "World"])
  ```

##### Resources
- [Hugging Face Embeddings Guide](https://huggingface.co/docs/transformers/pipeline_tutorial#embeddings)
- [LangChain Embeddings Documentation](https://python.langchain.com/docs/modules/data_connection/text_embedding/)
- [Sentence Transformers GitHub](https://github.com/UKPLab/sentence-transformers)

#### Exploring Vector Stores

Vector stores, or vector databases, are specialized databases designed to store and query vectors efficiently, enabling fast similarity searches. The lecture covered types like FAISS (in-memory), Chroma (on-disk), and cloud-based options like Pinecone and Weaviate, and further exploration can optimize RAG system performance.

##### Types of Vector Stores
- **In-Memory**: Fast but limited by RAM, suitable for small to medium datasets (e.g., FAISS).
- **On-Disk**: Persistent but slower, ideal for larger datasets with storage needs (e.g., Chroma).
- **Cloud-Based**: Scalable and managed, suitable for production environments (e.g., Pinecone, Weaviate).

##### Key Features to Explore
- **Indexing Techniques**:
  - **Flat Index**: Exact search, suitable for small datasets (<100,000 rows).
  - **HNSW (Hierarchical Navigable Small World)**: Approximate search, faster for large datasets, using graph-based navigation.
  - **IVF (Inverted File Index)**: Cluster-based, efficient for very large datasets, reducing search space.
- **Similarity Metrics**: 
  - **Cosine Similarity**: Measures the angle between vectors, range -1 to 1, best for text data.
  - **L2 Distance (Euclidean Distance)**: Measures straight-line distance, range 0 to ∞, suitable for data where magnitude matters.
- **Metadata Support**: Many vector stores allow storing metadata (e.g., document source, page number) for filtering, enhancing retrieval flexibility.

##### Popular Vector Stores
Below is a table comparing popular vector stores:

| Vector Store | Type        | Key Features                              | Example Use Case         |
|--------------|-------------|-------------------------------------------|--------------------------|
| FAISS        | In-Memory   | Fast, supports HNSW, IVF indexing         | Local prototyping        |
| Pinecone     | Cloud-Based | Scalable, metadata filtering, high uptime | Production RAG systems   |
| Chroma       | On-Disk     | Persistent, open-source, easy setup       | Offline data storage     |
| Weaviate     | Cloud-Based | Advanced querying, graph-based search     | Complex retrieval tasks  |

- **FAISS**:
  - Best for in-memory storage and small to medium datasets. Example:
    ```python
    from langchain.vectorstores import FAISS
    from langchain.embeddings import HuggingFaceEmbeddings
    embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
    vector_store = FAISS.from_texts(["AI is future", "AI is powerful"], embeddings)
    results = vector_store.similarity_search("Tell me about AI", k=2)
    ```
  - **Resource**: [FAISS Documentation](https://github.com/facebookresearch/faiss)

- **Pinecone**:
  - Cloud-based, scalable, supports filtering by metadata. Example:
    ```python
    import pinecone
    pinecone.init(api_key="your_api_key", environment="your_env")
    index = pinecone.Index("your_index_name")
    index.upsert([{"id": "1", "values": [0.1, 0.2, 0.3], "metadata": {"source": "doc1"}}])
    query_response = index.query(top_k=2, vector=[0.1, 0.2, 0.3])
    ```
  - **Resource**: [Pinecone Documentation](https://docs.pinecone.io/docs/overview)

- **Chroma**:
  - Open-source, supports on-disk storage. Example:
    ```python
    from chromadb import Client
    client = Client()
    collection = client.get_or_create_collection(name="my_collection")
    collection.add(documents=["AI is future"], metadatas=[{"source": "doc1"}])
    results = collection.query(query_texts=["Tell me about AI"], n_results=2)
    ```
  - **Resource**: [ChromaDB Documentation](https://docs.trychroma.com/)

- **Weaviate**:
  - Cloud-based, supports advanced querying. Example:
    ```python
    import weaviate
    client = weaviate.Client("your_weaviate_url")
    client.schema.get()
    client.data_object.create(data={"text": "AI is future"}, collection_name="Articles")
    result = client.query.get("Articles", ["text"]).with_near_text({"concepts": ["AI"]}).do()
    ```
  - **Resource**: [Weaviate Documentation](https://weaviate.io/developers/weaviate/current/)

##### Resources
- [Vector Databases Comparison](https://www.pinecone.io/learn/vector-database/)
- [LangChain Vector Stores](https://python.langchain.com/docs/modules/data_connection/vectorstores/)

#### Exploring Similarity Search Techniques

Similarity search is the process of finding the most similar vectors to a given query vector, a core component of vector databases and RAG systems. The lecture discussed metrics like cosine similarity and L2 distance, and further exploration can optimize retrieval performance.

##### Similarity Metrics
- **Cosine Similarity**:
  - Formula: \( \text{similarity} = \frac{A \cdot B}{\|A\| \|B\|} \)
  - Range: -1 (opposite) to 1 (identical)
  - Best for text data where direction matters more than magnitude, commonly used in semantic search.
- **L2 Distance (Euclidean Distance)**:
  - Formula: \( \text{distance} = \sqrt{\sum_{i=1}^{n} (A_i - B_i)^2} \)
  - Range: 0 (identical) to ∞
  - Best for data where magnitude is important, such as image features.

##### Search Techniques
- **Exact Search**:
  - Uses brute-force comparison, e.g., flat index in FAISS, ensuring accuracy but slow for large datasets.
- **Approximate Search**:
  - Uses indexing techniques like HNSW or IVF to speed up search, trading off some accuracy for performance, ideal for large-scale applications.
- **Hybrid Search**:
  - Combines keyword search with vector search, enhancing results by leveraging both lexical and semantic matching, often used in search engines.

##### Implementing Similarity Search
Examples include:
- Using FAISS:
  ```python
  from langchain.vectorstores import FAISS
  from langchain.embeddings import HuggingFaceEmbeddings
  embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
  vector_store = FAISS.from_texts(["AI is future", "AI is powerful"], embeddings)
  results = vector_store.similarity_search("Tell me about AI", k=2)
  ```
- Using Pinecone:
  ```python
  import pinecone
  pinecone.init(api_key="your_api_key", environment="your_env")
  index = pinecone.Index("your_index_name")
  query_response = index.query(top_k=2, vector=[0.1, 0.2, 0.3])
  ```

##### Advanced Techniques
- **Filtering**: Use metadata to filter results, e.g., only return documents from a specific source, enhancing relevance.
- **Re-Ranking**: Use a secondary model, such as a transformer, to re-rank the top-k results for better accuracy, improving user experience.
- **Semantic Search**: Combine embeddings with LLMs for context-aware search, enabling more nuanced query understanding.

##### Resources
- [FAISS Similarity Search](https://github.com/facebookresearch/faiss/wiki/Faiss-command-line-interface)
- [Pinecone Similarity Search](https://docs.pinecone.io/docs/query)
- [LangChain Similarity Search](https://python.langchain.com/docs/modules/data_connection/vectorstores)

#### Practical Steps for Exploration

To deepen your understanding, follow these steps:
1. **Set Up a Local Vector Store**: Use FAISS or Chroma for quick experimentation. Example with FAISS:
   ```python
   from langchain.vectorstores import FAISS
   from langchain.embeddings import HuggingFaceEmbeddings
   embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
   vector_store = FAISS.from_texts(["AI is future", "AI is powerful"], embeddings)
   results = vector_store.similarity_search("Tell me about AI", k=2)
   ```
2. **Experiment with Different Embeddings**: Compare OpenAI, Hugging Face, and other models using LangChain for seamless integration.
3. **Try Cloud-Based Vector Stores**: Sign up for Pinecone or Weaviate and experiment with their APIs. Example with Pinecone:
   ```python
   import pinecone
   pinecone.init(api_key="your_api_key", environment="your_env")
   index = pinecone.Index("your_index_name")
   index.upsert([{"id": "1", "values": [0.1, 0.2, 0.3], "metadata": {"source": "doc1"}}])
   query_response = index.query(top_k=2, vector=[0.1, 0.2, 0.3])
   ```
4. **Build a Simple RAG System**: Integrate embeddings, vector stores, and an LLM using LangChain. Example:
   ```python
   from langchain.chains import RetrievalQA
   from langchain.llms import OpenAI
   from langchain.vectorstores import FAISS
   from langchain.embeddings import HuggingFaceEmbeddings
   embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
   vector_store = FAISS.from_texts(["AI is future", "AI is powerful"], embeddings)
   qa = RetrievalQA.from_chain_type(llm=OpenAI(), chain_type="stuff", retriever=vector_store.as_retriever())
   response = qa.run("What is AI?")
   ```
5. **Explore Advanced Topics**: Learn about hybrid search, re-ranking, and filtering, and experiment with large datasets to understand indexing trade-offs.

#### Conclusion

Exploring embeddings, vector stores, and similarity search techniques is essential for enhancing AI applications like RAG systems. By leveraging tools like Hugging Face, FAISS, Pinecone, and LangChain, and following practical steps, practitioners can optimize performance and scalability. The provided resources and examples offer a starting point for deeper research and implementation, ensuring a comprehensive understanding as of 03:02 PM IST on Wednesday, June 18, 2025.

---

### Key Citations
- [OpenAI Embeddings Documentation](https://platform.openai.com/docs/guides/embeddings)
- [Hugging Face Embeddings](https://huggingface.co/models?filter=sentence-transformers)
- [Hugging Face Embeddings Guide](https://huggingface.co/docs/transformers/pipeline_tutorial#embeddings)
- [LangChain Embeddings Documentation](https://python.langchain.com/docs/modules/data_connection/text_embedding/)
- [Sentence Transformers GitHub](https://github.com/UKPLab/sentence-transformers)
- [FAISS Documentation](https://github.com/facebookresearch/faiss)
- [Pinecone Documentation](https://docs.pinecone.io/docs/overview)
- [ChromaDB Documentation](https://docs.trychroma.com/)
- [Weaviate Documentation](https://weaviate.io/developers/weaviate/current/)
- [Vector Databases Comparison](https://www.pinecone.io/learn/vector-database/)
- [LangChain Vector Stores](https://python.langchain.com/docs/modules/data_connection/vectorstores/)
- [FAISS Similarity Search](https://github.com/facebookresearch/faiss/wiki/Faiss-command-line-interface)
- [Pinecone Similarity Search](https://docs.pinecone.io/docs/query)
- [LangChain Similarity Search](https://python.langchain.com/docs/modules/data_connection/vectorstores)

### Pinecone

In [91]:
from langchain_huggingface import HuggingFaceEmbeddings
embeddings=HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

In [92]:
embeddings.embed_query("hello AI")

[-0.033388204872608185, 0.03453974053263664, 0.05947452038526535, 0.05928610637784004, -0.06353536248207092, -0.06819581985473633, 0.08823318779468536, 0.03444082289934158, -0.032785143703222275, -0.01581503450870514, 0.020981701090931892, -0.01834029145538807, -0.039832133799791336, -0.08047077804803848, -0.014469215646386147, 0.0332648828625679, 0.01425927970558405, -0.03404996171593666, -0.142915740609169, -0.023083269596099854, -0.02138008177280426, 0.002633549040183425, -0.04729273170232773, -0.010752758011221886, -0.06866797059774399, 0.031125066801905632, 0.0759459063410759, 0.0011282657505944371, 0.011631992645561695, -0.036039240658283234, 0.0448375940322876, 0.018390778452157974, 0.12672795355319977, -0.0013597294455394149, 0.008206664584577084, 0.06909965723752975, -0.08076354116201401, -0.05841318145394325, 0.05375447869300842, 0.02622760273516178, -0.006828595884144306, -0.05635837838053703, 0.003292993875220418, -0.0725017637014389, 0.06960922479629517, 0.0316743887960910

In [93]:
len(embeddings.embed_query("hello AI"))

384

In [94]:
from langchain_google_genai import GoogleGenerativeAIEmbeddings
embeddings = GoogleGenerativeAIEmbeddings(model="models/embedding-001")

In [95]:
embeddings.embed_query("Hello AI")

[0.01908188685774803, -0.04838583618402481, -0.0033970330841839314, -0.015432494692504406, 0.026915451511740685, -0.037899527698755264, 0.03683774173259735, 0.0024586953222751617, 0.031139591708779335, -0.002974053379148245, 0.05297260358929634, 0.027224618941545486, -0.03135930001735687, -0.03521350398659706, 0.012696987949311733, -0.03398113697767258, -0.005759889259934425, 0.04882349446415901, -0.025584226474165916, -0.016702925786376, 0.03510289266705513, -0.0072209034115076065, -0.011071284301578999, -0.03638654947280884, 0.02125084027647972, 0.018635960295796394, 0.022123489528894424, -0.053073909133672714, -0.03174823150038719, 0.03385208174586296, -0.03267931193113327, 0.05955952778458595, -0.04031715542078018, -0.01112906914204359, 0.04654634743928909, -0.05826421454548836, 0.03411427512764931, 0.019681427627801895, 0.008696145378053188, -0.004346166737377644, 0.0029152834322303534, -0.08902806788682938, -0.015501082874834538, -0.01798322983086109, 0.014601176604628563, -0.001

In [96]:
len(embeddings.embed_query("Hello AI"))

768

In [100]:
print(os.getenv("PINECONE_API_KEY"))

None


In [103]:
from pinecone import Pinecone
import os
pinecone_api_key=os.getenv("PINECONE_API_KEY")

In [105]:
pc=Pinecone(api_key=pinecone_api_key)
index_name="agenticbatch2"
pc.has_index(index_name)

False

In [107]:
from pinecone import ServerlessSpec
#creating a index
if not pc.has_index(index_name):
    pc.create_index(
    name=index_name,
    dimension=768,
    metric="cosine",
    spec=ServerlessSpec(cloud="aws",region="us-east-1")    
)

In [108]:
pc.has_index(index_name)

True

In [109]:
#loading the index
index=pc.Index(index_name)

In [110]:
from langchain_pinecone import PineconeVectorStore
vector_store=PineconeVectorStore(index=index,embedding=embeddings)

In [111]:
results = vector_store.similarity_search("what is a langchain?")

In [112]:
results

[]

In [113]:
from uuid import uuid4
from langchain_core.documents import Document

document_1 = Document(
    page_content="I had chocolate chip pancakes and scrambled eggs for breakfast this morning.",
    metadata={"source": "tweet"},#additional info
)

document_2 = Document(
    page_content="The weather forecast for tomorrow is cloudy and overcast, with a high of 62 degrees.",
    metadata={"source": "news"},
)

document_3 = Document(
    page_content="Building an exciting new project with LangChain - come check it out!",
    metadata={"source": "tweet"},
)

document_4 = Document(
    page_content="Robbers broke into the city bank and stole $1 million in cash.",
    metadata={"source": "news"},
)

document_5 = Document(
    page_content="Wow! That was an amazing movie. I can't wait to see it again.",
    metadata={"source": "tweet"},
)

document_6 = Document(
    page_content="Is the new iPhone worth the price? Read this review to find out.",
    metadata={"source": "website"},
)

document_7 = Document(
    page_content="The top 10 soccer players in the world right now.",
    metadata={"source": "website"},
)

document_8 = Document(
    page_content="LangGraph is the best framework for building stateful, agentic applications!",
    metadata={"source": "tweet"},
)

document_9 = Document(
    page_content="The stock market is down 500 points today due to fears of a recession.",
    metadata={"source": "news"},
)

document_10 = Document(
    page_content="I have a bad feeling I am going to get deleted :(",
    metadata={"source": "tweet"},
)


In [114]:
documents = [
    document_1,
    document_2,
    document_3,
    document_4,
    document_5,
    document_6,
    document_7,
    document_8,
    document_9,
    document_10,
]

In [115]:
documents

[Document(metadata={'source': 'tweet'}, page_content='I had chocolate chip pancakes and scrambled eggs for breakfast this morning.'), Document(metadata={'source': 'news'}, page_content='The weather forecast for tomorrow is cloudy and overcast, with a high of 62 degrees.'), Document(metadata={'source': 'tweet'}, page_content='Building an exciting new project with LangChain - come check it out!'), Document(metadata={'source': 'news'}, page_content='Robbers broke into the city bank and stole $1 million in cash.'), Document(metadata={'source': 'tweet'}, page_content="Wow! That was an amazing movie. I can't wait to see it again."), Document(metadata={'source': 'website'}, page_content='Is the new iPhone worth the price? Read this review to find out.'), Document(metadata={'source': 'website'}, page_content='The top 10 soccer players in the world right now.'), Document(metadata={'source': 'tweet'}, page_content='LangGraph is the best framework for building stateful, agentic applications!'), D

In [116]:
len(documents)

10

In [117]:
range(len(documents))

range(0, 10)

In [118]:
for _ in range(len(documents)):
    print(_)
    print(str(uuid4()))
    

0
d1aaae41-524b-42b6-bc9e-227af0b6a7c2
1
c22189f7-771b-4cd1-9ff4-756954763ac8
2
932545ae-fe30-4344-b11f-b6b3986b3111
3
24f8f325-6426-422c-b31f-b25ebff168be
4
a54b78cc-d7c4-4afd-809f-6d853e1580d6
5
e49b9565-ff6c-4ab0-94f0-d01417f62ceb
6
be87dd98-34a9-4aca-9383-024fe84abb77
7
a85694cd-d7c8-40e6-abbe-959c934275d1
8
88c06dec-a971-4482-8ba3-60a3f33280f8
9
2d543e03-b3ce-4ad2-ba74-da9db9c3659c


In [119]:
#universal indentification number
uuids = [str(uuid4()) for _ in range(len(documents))]

In [120]:
uuids

['89cfb98d-5f45-421f-b99e-507e6a294ef0', 'ce5a61a7-2fef-4e38-912c-d1fcc80b618b', 'de8d88a9-f96e-4a56-b118-20b6788ce166', '9ebc6b3e-93a9-4815-abd8-4f86ed6f1224', '2f4c3e63-2682-4ea8-b3ca-c81e6e04088f', '2f19f3a3-f4e7-4e65-aed8-7286481ca847', 'df518962-d33e-4b28-a2f8-07ca205e2769', '9226c48c-d478-4c17-8f42-589e0c9fb7a0', '6d786b23-47ac-43b0-aba0-7e8c9837289c', '9ee2a649-3ca1-4fda-a2c1-13c1cdf69f53']

In [121]:
vector_store.add_documents(documents=documents, ids=uuids)

['89cfb98d-5f45-421f-b99e-507e6a294ef0', 'ce5a61a7-2fef-4e38-912c-d1fcc80b618b', 'de8d88a9-f96e-4a56-b118-20b6788ce166', '9ebc6b3e-93a9-4815-abd8-4f86ed6f1224', '2f4c3e63-2682-4ea8-b3ca-c81e6e04088f', '2f19f3a3-f4e7-4e65-aed8-7286481ca847', 'df518962-d33e-4b28-a2f8-07ca205e2769', '9226c48c-d478-4c17-8f42-589e0c9fb7a0', '6d786b23-47ac-43b0-aba0-7e8c9837289c', '9ee2a649-3ca1-4fda-a2c1-13c1cdf69f53']

In [122]:
results = vector_store.similarity_search("what langchain provides to us?",k=1)

In [123]:
results

[Document(id='de8d88a9-f96e-4a56-b118-20b6788ce166', metadata={'source': 'tweet'}, page_content='Building an exciting new project with LangChain - come check it out!')]

In [124]:
results = vector_store.similarity_search("what langchain provides to us?",filter={"source": "tweet"})

In [125]:
results

[Document(id='de8d88a9-f96e-4a56-b118-20b6788ce166', metadata={'source': 'tweet'}, page_content='Building an exciting new project with LangChain - come check it out!'), Document(id='9226c48c-d478-4c17-8f42-589e0c9fb7a0', metadata={'source': 'tweet'}, page_content='LangGraph is the best framework for building stateful, agentic applications!'), Document(id='2f4c3e63-2682-4ea8-b3ca-c81e6e04088f', metadata={'source': 'tweet'}, page_content="Wow! That was an amazing movie. I can't wait to see it again."), Document(id='89cfb98d-5f45-421f-b99e-507e6a294ef0', metadata={'source': 'tweet'}, page_content='I had chocolate chip pancakes and scrambled eggs for breakfast this morning.')]

In [126]:
retriever=vector_store.as_retriever(
    search_type="similarity_score_threshold",
    search_kwargs={"score_threshold": 0.7} #hyperparameter
)

In [127]:
retriever.invoke("langchain")

[Document(id='de8d88a9-f96e-4a56-b118-20b6788ce166', metadata={'source': 'tweet'}, page_content='Building an exciting new project with LangChain - come check it out!'), Document(id='9226c48c-d478-4c17-8f42-589e0c9fb7a0', metadata={'source': 'tweet'}, page_content='LangGraph is the best framework for building stateful, agentic applications!'), Document(id='9ee2a649-3ca1-4fda-a2c1-13c1cdf69f53', metadata={'source': 'tweet'}, page_content='I have a bad feeling I am going to get deleted :('), Document(id='2f4c3e63-2682-4ea8-b3ca-c81e6e04088f', metadata={'source': 'tweet'}, page_content="Wow! That was an amazing movie. I can't wait to see it again.")]

In [128]:
retriever.invoke("google")

[Document(id='de8d88a9-f96e-4a56-b118-20b6788ce166', metadata={'source': 'tweet'}, page_content='Building an exciting new project with LangChain - come check it out!'), Document(id='9ee2a649-3ca1-4fda-a2c1-13c1cdf69f53', metadata={'source': 'tweet'}, page_content='I have a bad feeling I am going to get deleted :('), Document(id='9226c48c-d478-4c17-8f42-589e0c9fb7a0', metadata={'source': 'tweet'}, page_content='LangGraph is the best framework for building stateful, agentic applications!'), Document(id='2f19f3a3-f4e7-4e65-aed8-7286481ca847', metadata={'source': 'website'}, page_content='Is the new iPhone worth the price? Read this review to find out.')]

In [129]:
from langchain_google_genai import ChatGoogleGenerativeAI
model=ChatGoogleGenerativeAI(model='gemini-1.5-flash')

In [130]:
from langchain import hub
prompt = hub.pull("rlm/rag-prompt")

In [131]:
import pprint
pprint.pprint(prompt.messages)

[HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['context', 'question'], input_types={}, partial_variables={}, template="You are an assistant for question-answering tasks. Use the following pieces of retrieved context to answer the question. If you don't know the answer, just say that you don't know. Use three sentences maximum and keep the answer concise.\nQuestion: {question} \nContext: {context} \nAnswer:"), additional_kwargs={})]


In [132]:
from langchain_core.prompts import PromptTemplate

In [133]:
prompt=PromptTemplate(
    template="""You are an assistant for question-answering tasks. Use the following pieces of retrieved context to answer the question. If you don't know the answer, just say that you don't know. Use three sentences maximum and keep the answer concise.\nQuestion: {question} \nContext: {context} \nAnswer:""",
    input_variables=['context', 'question']
)

In [134]:
prompt

PromptTemplate(input_variables=['context', 'question'], input_types={}, partial_variables={}, template="You are an assistant for question-answering tasks. Use the following pieces of retrieved context to answer the question. If you don't know the answer, just say that you don't know. Use three sentences maximum and keep the answer concise.\nQuestion: {question} \nContext: {context} \nAnswer:")

In [135]:
prompt.invoke({"question":"what is a langchain?","context":"langchain is very super framework for LLM."})

StringPromptValue(text="You are an assistant for question-answering tasks. Use the following pieces of retrieved context to answer the question. If you don't know the answer, just say that you don't know. Use three sentences maximum and keep the answer concise.\nQuestion: what is a langchain? \nContext: langchain is very super framework for LLM. \nAnswer:")

In [136]:
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough

In [137]:
def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)

In [138]:
rag_chain = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | prompt
    | model
    | StrOutputParser()
)

In [139]:
rag_chain.invoke("what is llama model?")

"I don't know.  The provided text does not contain information about Llama models."


## second assisgnment is: take a multiple pdf with text,image,table
1. fetch the data from pdf
2. at lesat there should be 200 pages
3. if chunking(use the sementic chunking technique) required do chunking and then embedding
4. store it inside the vector database(use any of them 1. mongodb 2. astradb 3. opensearch 4.milvus) ## i have not discuss then you need to explore
5. create a index with all three index machnism(Flat, HNSW, IVF) ## i have not discuss then you need to explore
6. create a retriever pipeline
7. check the retriever time(which one is fastet)
8. print the accuray score of every similarity search
9. perform the reranking either using BM25 or MMR ## i have not discuss then you need to explore
10. then write a prompt template
11. generte a oputput through llm
12. render that output over the DOCx ## i have not discuss then you need to explore
as a additional tip: you can follow rag playlist from my youtube

# Last